const CATEGORY_STYLES = {
  Wild: [
    { bg: 'bg-amber-100', text: 'text-amber-800' },
    { bg: 'bg-orange-100', text: 'text-orange-800' },
    { bg: 'bg-yellow-100', text: 'text-yellow-800' },
    { bg: 'bg-lime-100', text: 'text-lime-800' },
  ],
  Farm: [
    { bg: 'bg-green-100', text: 'text-green-800' },
    { bg: 'bg-emerald-100', text: 'text-emerald-800' },
    { bg: 'bg-lime-100', text: 'text-lime-800' },
    { bg: 'bg-teal-100', text: 'text-teal-800' },
  ],
  Pet: [
    { bg: 'bg-sky-100', text: 'text-sky-800' },
    { bg: 'bg-blue-100', text: 'text-blue-800' },
    { bg: 'bg-indigo-100', text: 'text-indigo-800' },
    { bg: 'bg-violet-100', text: 'text-violet-800' },
  ],
  Bird: [
    { bg: 'bg-cyan-100', text: 'text-cyan-800' },
    { bg: 'bg-slate-100', text: 'text-slate-800' },
    { bg: 'bg-blue-100', text: 'text-blue-800' },
    { bg: 'bg-teal-100', text: 'text-teal-800' },
  ],
  Ocean: [
    { bg: 'bg-blue-100', text: 'text-blue-900' },
    { bg: 'bg-cyan-100', text: 'text-cyan-900' },
    { bg: 'bg-sky-100', text: 'text-sky-900' },
    { bg: 'bg-indigo-100', text: 'text-indigo-900' },
  ],
  Bug: [
    { bg: 'bg-rose-100', text: 'text-rose-800' },
    { bg: 'bg-pink-100', text: 'text-pink-800' },
    { bg: 'bg-fuchsia-100', text: 'text-fuchsia-800' },
    { bg: 'bg-purple-100', text: 'text-purple-800' },
  ],
};

const CATEGORY_EMOJIS = {
  Wild: [
    '\uD83E\uDD81',
    '\uD83D\uDC2F',
    '\uD83D\uDC06',
    '\uD83D\uDC3A',
    '\uD83D\uDC3B',
    '\uD83D\uDC3C',
    '\uD83D\uDC18',
    '\uD83E\uDD8F',
    '\uD83E\uDD92',
    '\uD83D\uDC17',
    '\uD83E\uDD8C',
    '\uD83D\uDC12',
    '\uD83E\uDD8D',
    '\uD83D\uDC2A',
    '\uD83D\uDC03',
    '\uD83E\uDD98',
    '\uD83E\uDDA5',
    '\uD83E\uDDA8',
    '\uD83E\uDD94',
  ],
  Farm: [
    '\uD83D\uDC04',
    '\uD83D\uDC02',
    '\uD83D\uDC10',
    '\uD83D\uDC11',
    '\uD83D\uDC34',
    '\uD83D\uDC16',
    '\uD83D\uDC37',
    '\uD83D\uDC14',
    '\uD83D\uDC13',
    '\uD83E\uDD83',
    '\uD83E\uDD86',
    '\uD83D\uDC07',
    '\uD83D\uDC08',
    '\uD83D\uDC15',
    '\uD83D\uDC2B',
    '\uD83E\uDD99',
    '\uD83C\uDF3E',
  ],
  Pet: [
    '\uD83D\uDC36',
    '\uD83D\uDC31',
    '\uD83D\uDC30',
    '\uD83D\uDC39',
    '\uD83D\uDC2D',
    '\uD83E\uDD9C',
    '\uD83D\uDC20',
    '\uD83D\uDC1F',
    '\uD83D\uDC22',
    '\uD83D\uDC38',
    '\uD83E\uDD8E',
    '\uD83D\uDC0D',
    '\uD83E\uDD94',
  ],
  Bird: [
    '\uD83D\uDC26',
    '\uD83D\uDD4A',
    '\uD83E\uDD85',
    '\uD83E\uDD89',
    '\uD83E\uDD86',
    '\uD83D\uDC14',
    '\uD83D\uDC27',
    '\uD83E\uDD9A',
    '\uD83E\uDD83',
    '\uD83E\uDDA9',
    '\uD83E\uDDA2',
  ],
  Ocean: [
    '\uD83D\uDC1F',
    '\uD83D\uDC2C',
    '\uD83D\uDC33',
    '\uD83E\uDD88',
    '\uD83D\uDC19',
    '\uD83E\uDD91',
    '\uD83D\uDC1A',
    '\uD83D\uDC22',
    '\uD83E\uDD80',
    '\uD83E\uDD9E',
    '\uD83E\uDD90',
    '\uD83E\uDDAD',
    '\uD83C\uDF0A',
  ],
  Bug: [
    '\uD83E\uDD8B',
    '\uD83D\uDC1D',
    '\uD83D\uDC1E',
    '\uD83D\uDC1C',
    '\uD83D\uDC1B',
    '\uD83E\uDD9F',
    '\uD83E\uDD97',
    '\uD83D\uDD77',
    '\uD83D\uDC0C',
    '\uD83C\uDF3F',
    '\uD83D\uDC1B',
  ],
};

const CATEGORY_HABITATS = {
  Wild: ['jungle', 'savanna', 'rainforest', 'mountain forest', 'grasslands'],
  Farm: ['farmyard', 'barn', 'pasture', 'village farm', 'open fields'],
  Pet: ['home', 'backyard', 'aquarium', 'terrarium', 'cozy pet corner'],
  Bird: ['tree tops', 'open sky', 'wetlands', 'forest canopy', 'rocky cliffs'],
  Ocean: ['coral reef', 'deep ocean', 'coastal waters', 'kelp forest', 'open sea'],
  Bug: ['garden', 'forest floor', 'flower meadow', 'tree bark', 'pond edge'],
};

const CATEGORY_SOUNDS = {
  Wild: ['Roar!', 'Growl!', 'Howl!', 'Snort!', 'Trumpet!'],
  Farm: ['Moo!', 'Neigh!', 'Baa!', 'Oink!', 'Cluck!'],
  Pet: ['Meow!', 'Woof!', 'Chirp!', 'Squeak!', 'Purr!'],
  Bird: ['Chirp!', 'Tweet!', 'Screech!', 'Caw!', 'Hoot!'],
  Ocean: ['Splash!', 'Click!', 'Whistle!', 'Blub!', 'Whoosh!'],
  Bug: ['Buzz!', 'Click!', 'Flutter!', 'Hum!', 'Tick-tick!'],
};

const CATEGORY_FACTS = {
  Wild: [
    'I am brave and alert in the wild.',
    'I can move quickly when I need to find food.',
    'My senses help me survive every day.',
    'I use smart tricks to stay safe from danger.',
    'My body is built perfectly for nature adventures.',
  ],
  Farm: [
    'I help people on farms every season.',
    'I enjoy simple routines and fresh food.',
    'I am happiest when I have space to move around.',
    'I can be gentle, friendly, and hardworking.',
    'I am an important friend in farm life.',
  ],
  Pet: [
    'I love spending time with my human family.',
    'I enjoy playful games and cozy rest time.',
    'I can learn routines and respond to care.',
    'I feel safe when my home is calm and kind.',
    'I bring joy with my curious personality.',
  ],
  Bird: [
    'My wings and feathers help me explore.',
    'I use my beak in smart and useful ways.',
    'I can communicate with special calls.',
    'I am light, fast, and full of energy.',
    'I watch the world from high places.',
  ],
  Ocean: [
    'I am adapted for life in water.',
    'I glide smoothly through waves and currents.',
    'My body helps me swim with balance and speed.',
    'I survive in salty seas with unique skills.',
    'I explore colorful underwater worlds.',
  ],
  Bug: [
    'I may be tiny, but I have big survival skills.',
    'I move quickly and hide in small spaces.',
    'I play an important role in nature cycles.',
    'My body has cool patterns and tiny details.',
    'I help gardens and ecosystems in many ways.',
  ],
};

const CATEGORY_NAMES = {
  Wild: [
    'Lion',
    'Tiger',
    'Leopard',
    'Cheetah',
    'Jaguar',
    'Panther',
    'Snow Leopard',
    'Lynx',
    'Cougar',
    'Hyena',
    'Wolf',
    'Fox',
    'Jackal',
    'Brown Bear',
    'Polar Bear',
    'Giant Panda',
    'Koala',
    'Gorilla',
    'Chimpanzee',
    'Orangutan',
    'Baboon',
    'Mandrill',
    'Zebra',
    'Giraffe',
    'African Elephant',
    'Rhinoceros',
    'Hippopotamus',
    'Bison',
    'Cape Buffalo',
    'Antelope',
    'Gazelle',
    'Wildebeest',
    'Deer',
    'Moose',
    'Elk',
    'Desert Camel',
    'Mountain Llama',
    'Andean Alpaca',
    'Wild Boar',
    'Kangaroo',
    'Wallaby',
    'Platypus',
    'Wombat',
    'Sloth',
    'Armadillo',
    'Meerkat',
    'River Otter',
    'Raccoon',
    'Skunk',
    'Porcupine',
  ],
  Farm: [
    'Cow',
    'Bull',
    'Calf',
    'Water Buffalo',
    'Ox',
    'Goat',
    'Kid Goat',
    'Sheep',
    'Ram',
    'Lamb',
    'Horse',
    'Pony',
    'Donkey',
    'Mule',
    'Pig',
    'Sow',
    'Boar',
    'Piglet',
    'Chicken',
    'Rooster',
    'Hen',
    'Chick',
    'Turkey',
    'Farm Duck',
    'Farm Goose',
    'Gander',
    'Farm Quail',
    'Guinea Fowl',
    'Loft Pigeon',
    'Farm Rabbit',
    'Barn Cat',
    'Sheepdog',
    'Yak',
    'Domestic Camel',
    'Ranch Alpaca',
    'Ranch Llama',
    'Zebu',
    'Reindeer',
    'Farm Emu',
    'Farm Ostrich',
    'Muscovy Duck',
    'Silkie Chicken',
    'Jersey Cow',
    'Holstein Cow',
    'Merino Sheep',
    'Angora Goat',
    'Nubian Goat',
    'Clydesdale Horse',
    'Suffolk Sheep',
    'Berkshire Pig',
  ],
  Pet: [
    'Dog',
    'Cat',
    'Pet Rabbit',
    'Hamster',
    'Guinea Pig',
    'Ferret',
    'Mouse',
    'Rat',
    'Gerbil',
    'Chinchilla',
    'Hedgehog',
    'Pet Parrot',
    'Budgie',
    'Pet Canary',
    'Pet Cockatiel',
    'Lovebird',
    'Pet Finch',
    'Turtle',
    'Tortoise',
    'Goldfish',
    'Betta Fish',
    'Guppy',
    'Molly Fish',
    'Platy Fish',
    'Koi',
    'Axolotl',
    'Pet Frog',
    'Gecko',
    'Bearded Dragon',
    'Corn Snake',
    'Ball Python',
    'Hermit Crab',
    'Pet Tarantula',
    'Pet Stick Insect',
    'Fancy Mouse',
    'Fancy Rat',
    'Mini Pig',
    'Pomeranian',
    'Labrador',
    'Beagle',
    'Persian Cat',
    'Siamese Cat',
    'Maine Coon',
    'Ragdoll',
    'Lop Bunny',
    'Parakeet',
    'Pet Cockatoo',
    'Pet Macaw',
    'Sugar Glider',
    'Pug',
  ],
  Bird: [
    'Eagle',
    'Hawk',
    'Falcon',
    'Owl',
    'Sky Parrot',
    'Rainforest Macaw',
    'Jungle Cockatoo',
    'Pigeon',
    'Dove',
    'Sparrow',
    'Crow',
    'Raven',
    'Peacock',
    'Flamingo',
    'Pelican',
    'Stork',
    'Heron',
    'Crane',
    'Swan',
    'Wild Goose',
    'Wild Duck',
    'Kingfisher',
    'Woodpecker',
    'Hummingbird',
    'Robin',
    'Blue Jay',
    'Cardinal',
    'Forest Canary',
    'Forest Finch',
    'Budgerigar',
    'Wild Cockatiel',
    'Kiwi',
    'Ostrich',
    'Emu',
    'Penguin',
    'Albatross',
    'Seagull',
    'Tern',
    'Puffin',
    'Toucan',
    'Hornbill',
    'Vulture',
    'Kite Bird',
    'Condor',
    'Nightjar',
    'Quail Bird',
    'Partridge',
    'Pheasant',
    'Cuckoo',
    'Nightingale',
  ],
  Ocean: [
    'Dolphin',
    'Shark',
    'Whale',
    'Orca',
    'Octopus',
    'Squid',
    'Cuttlefish',
    'Jellyfish',
    'Sea Turtle',
    'Seahorse',
    'Sea Lion',
    'Seal',
    'Walrus',
    'Manatee',
    'Dugong',
    'Crab',
    'Lobster',
    'Shrimp',
    'Prawn',
    'Starfish',
    'Sea Urchin',
    'Sea Cucumber',
    'Clam',
    'Oyster',
    'Mussel',
    'Scallop',
    'Coral',
    'Eel',
    'Moray Eel',
    'Stingray',
    'Manta Ray',
    'Hammerhead Shark',
    'Blue Whale',
    'Humpback Whale',
    'Sperm Whale',
    'Narwhal',
    'Beluga Whale',
    'Clownfish',
    'Angelfish',
    'Surgeonfish',
    'Tuna',
    'Salmon',
    'Swordfish',
    'Marlin',
    'Barracuda',
    'Anchovy',
    'Sardine',
    'Pufferfish',
    'Lionfish',
    'Blobfish',
  ],
  Bug: [
    'Butterfly',
    'Bee',
    'Ladybug',
    'Ant',
    'Beetle',
    'Dragonfly',
    'Damselfly',
    'Grasshopper',
    'Cricket',
    'Locust',
    'Moth',
    'Mosquito',
    'Fly',
    'Housefly',
    'Firefly',
    'Termite',
    'Wasp',
    'Hornet',
    'Bumblebee',
    'Caterpillar',
    'Centipede',
    'Millipede',
    'Stick Insect',
    'Leaf Insect',
    'Praying Mantis',
    'Cockroach',
    'Flea',
    'Tick',
    'Louse',
    'Aphid',
    'Cicada',
    'Weevil',
    'Scarab Beetle',
    'Dung Beetle',
    'Rhinoceros Beetle',
    'Hercules Beetle',
    'Stag Beetle',
    'Earwig',
    'Silverfish',
    'Mayfly',
    'Stonefly',
    'Caddisfly',
    'Lacewing',
    'Assassin Bug',
    'Water Strider',
    'Goliath Beetle',
    'Glowworm',
    'Black Widow Spider',
    'Tarantula Spider',
    'Jumping Spider',
  ],
};

const CATEGORY_TARGET = 50;

Object.entries(CATEGORY_NAMES).forEach(([category, names]) => {
  if (names.length !== CATEGORY_TARGET) {
    throw new Error(`[animalsData] ${category} must contain exactly ${CATEGORY_TARGET} animals, found ${names.length}.`);
  }
});

const toSlug = (value) =>
  String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const getCycleValue = (values, index) => values[index % values.length];

const buildAnimalRecord = (category, name, index) => {
  const style = getCycleValue(CATEGORY_STYLES[category], index);
  const habitat = getCycleValue(CATEGORY_HABITATS[category], index);
  const sound = getCycleValue(CATEGORY_SOUNDS[category], index);
  const fact = getCycleValue(CATEGORY_FACTS[category], index);
  const emoji = getCycleValue(CATEGORY_EMOJIS[category], index);
  const id = `${category.toLowerCase()}-${toSlug(name)}`;

  const quizClue = `${fact} I am usually found in the ${habitat}.`;

  return {
    id,
    name,
    category,
    emoji,
    sound,
    soundFile: `/sounds/animals/${category.toLowerCase()}/${id}.mp3`,
    habitat,
    quizClue,
    bg: style.bg,
    text: style.text,
    bio: `Who am I? I am ${name}. ${quizClue}`,
  };
};

export const ANIMALS_DATA = Object.entries(CATEGORY_NAMES).flatMap(([category, names]) =>
  names.map((name, index) => buildAnimalRecord(category, name, index))
);

const OPTION_OFFSETS = [17, 43, 79, 131, 173, 211, 257];

const buildQuestionOptions = (correctIndex) => {
  const options = [ANIMALS_DATA[correctIndex].name];
  let cursor = 0;

  while (options.length < 4 && cursor < 80) {
    const offset = OPTION_OFFSETS[cursor % OPTION_OFFSETS.length] + cursor * 3;
    const candidate = ANIMALS_DATA[(correctIndex + offset) % ANIMALS_DATA.length]?.name;
    if (candidate && !options.includes(candidate)) {
      options.push(candidate);
    }
    cursor += 1;
  }

  const rotateBy = correctIndex % options.length;
  return [...options.slice(rotateBy), ...options.slice(0, rotateBy)];
};

const buildSafariQuestion = (animal, index) => {
  let questionText = '';

  if (index < 34) {
    questionText = `Which animal makes this sound: "${animal.sound}"?`;
  } else if (index < 67) {
    questionText = `Who am I? I usually live in the ${animal.habitat}.`;
  } else {
    questionText = `Who am I? ${animal.quizClue}`;
  }

  return {
    id: `safari-master-${index + 1}`,
    question: questionText,
    answer: animal.name,
    acceptedAnswers: [animal.name],
    options: buildQuestionOptions(index),
  };
};

export const SAFARI_MASTER_QUIZ_QUESTIONS = ANIMALS_DATA.slice(0, 100).map((animal, index) =>
  buildSafariQuestion(animal, index)
);

export default ANIMALS_DATA;
