export const CHARACTER_PROFILES = [
  {
    key: 'aiko',
    name: 'Aiko',
    cardTitle: 'AIKO BIO',
    route: '/aiko-bio',
    emoji: '\u{1F31F}',
    colorTheme: 'Gold / Yellow',
    specialHobby: 'Fearless Leader & Positive Energy',
    bio: 'Fearless leader and best friend, full of positive energy and mystery-solving ideas.',
    card: {
      color: '#facc15',
      shadowDark: '#b8860b',
      shadowLight: '#fde68a',
      innerLight: '#fef3c7',
      innerDark: '#a16207',
      textClass: 'text-slate-900',
      pillBg: '#fde68a',
      pillTextClass: 'text-amber-900',
    },
  },
  {
    key: 'niko',
    name: 'Niko',
    cardTitle: 'NIKO BIO',
    route: '/niko-bio',
    emoji: '\u{1F3C3}',
    colorTheme: 'RED',
    specialHobby: 'Sports, Fitness & Teamwork',
    bio: 'Energetic and brave athlete, teaches fitness and never gives up on a challenge.',
    card: {
      color: '#ef4444',
      shadowDark: '#7f1d1d',
      shadowLight: '#fca5a5',
      innerLight: '#fecaca',
      innerDark: '#b91c1c',
      textClass: 'text-white',
      pillBg: '#fca5a5',
      pillTextClass: 'text-red-950',
    },
  },
  {
    key: 'kinu',
    name: 'Kinu',
    cardTitle: 'KINU BIO',
    route: '/kinu-bio',
    emoji: '\u{1F3A8}',
    colorTheme: 'Blue / Azure',
    specialHobby: 'Art, Music & Creative Ideas',
    bio: 'Creative artist with a gentle heart, always has sketchbooks and magical, colorful ideas.',
    card: {
      color: '#3b82f6',
      shadowDark: '#1e3a8a',
      shadowLight: '#93c5fd',
      innerLight: '#bfdbfe',
      innerDark: '#1d4ed8',
      textClass: 'text-white',
      pillBg: '#93c5fd',
      pillTextClass: 'text-blue-950',
    },
  },
  {
    key: 'mimi',
    name: 'Mimi',
    cardTitle: 'MIMI BIO',
    route: '/mimi-bio',
    emoji: '\u{1F4D6}',
    colorTheme: 'Soft Pink / Magenta',
    specialHobby: 'Puzzles, Books & "Why/How" Questions',
    bio: 'Smartest kid, loves "Why" and "How" questions, solving tough puzzles with her sharp brain.',
    card: {
      color: '#ec4899',
      shadowDark: '#9d174d',
      shadowLight: '#f9a8d4',
      innerLight: '#fbcfe8',
      innerDark: '#be185d',
      textClass: 'text-white',
      pillBg: '#f9a8d4',
      pillTextClass: 'text-pink-950',
    },
  },
  {
    key: 'miko',
    name: 'Miko',
    cardTitle: 'MIKO BIO',
    route: '/miko-bio',
    emoji: '\u{1F331}',
    colorTheme: 'Lime Green',
    specialHobby: 'Nature, Gardening & Earth Defense',
    bio: 'Nature-lover and Earth-defender, loves exploring plants, animals, and gardening.',
    card: {
      color: '#84cc16',
      shadowDark: '#3f6212',
      shadowLight: '#d9f99d',
      innerLight: '#ecfccb',
      innerDark: '#4d7c0f',
      textClass: 'text-slate-900',
      pillBg: '#d9f99d',
      pillTextClass: 'text-lime-950',
    },
  },
  {
    key: 'chiko',
    name: 'Chiko',
    cardTitle: 'CHIKO BIO',
    route: '/learning-zone/chiko',
    emoji: '\u{1F916}',
    colorTheme: 'Teal / Cyan',
    specialHobby: 'Gadgets, Coding & Robot Inventions',
    bio: 'Tech-genius and inventor, loves gadgets, coding, and dreaming about future technology.',
    card: {
      color: '#06b6d4',
      shadowDark: '#155e75',
      shadowLight: '#a5f3fc',
      innerLight: '#cffafe',
      innerDark: '#0e7490',
      textClass: 'text-slate-900',
      pillBg: '#a5f3fc',
      pillTextClass: 'text-cyan-950',
    },
  },
];

export const CHARACTER_PROFILE_BY_KEY = CHARACTER_PROFILES.reduce((accumulator, profile) => {
  accumulator[profile.key] = profile;
  return accumulator;
}, {});
