export const CHARACTER_PROFILES = [
  {
    key: 'aiko',
    name: 'Aiko',
    cardTitle: 'AIKO BIO',
    route: '/aiko-bio',
    emoji: '\u{1F31F}',
    colorTheme: 'Golden Yellow',
    specialHobby: 'Fearless Leader & Positive Energy',
    bio: 'Fearless leader and best friend, full of positive energy and mystery-solving ideas.',
    gemstone: 'Yellow Sapphire',
    card: {
      color: '#fbbf24',
      shadowDark: '#b45309',
      shadowLight: '#fde68a',
      innerLight: '#fef3c7',
      innerDark: '#92400e',
      textClass: 'text-slate-900',
      pillBg: '#fde68a',
      pillTextClass: 'text-amber-900',
    },
  },
  {
    key: 'niko',
    name: 'Niko',
    cardTitle: 'NIKO BIO',
    route: '/niko-bio',
    emoji: '\u{1F3C3}',
    colorTheme: 'Soft Red',
    specialHobby: 'Sports, Fitness & Teamwork',
    bio: 'Energetic and brave athlete, teaches fitness and never gives up on a challenge.',
    gemstone: 'Red Beryl',
    card: {
      color: '#fca5a5',
      shadowDark: '#991b1b',
      shadowLight: '#fecaca',
      innerLight: '#fee2e2',
      innerDark: '#b91c1c',
      textClass: 'text-slate-900',
      pillBg: '#fecaca',
      pillTextClass: 'text-red-950',
    },
  },
  {
    key: 'kinu',
    name: 'Kinu',
    cardTitle: 'KINU BIO',
    route: '/kinu-bio',
    emoji: '\u{1F3A8}',
    colorTheme: 'Sky Blue',
    specialHobby: 'Art, Music & Creative Ideas',
    bio: 'Creative artist with a gentle heart, always has sketchbooks and magical, colorful ideas.',
    gemstone: 'Jeremejevite',
    card: {
      color: '#7dd3fc',
      shadowDark: '#0369a1',
      shadowLight: '#bae6fd',
      innerLight: '#e0f2fe',
      innerDark: '#0ea5e9',
      textClass: 'text-slate-900',
      pillBg: '#a5f3fc',
      pillTextClass: 'text-cyan-950',
    },
  },
  {
    key: 'mimi',
    name: 'Mimi',
    cardTitle: 'MIMI BIO',
    route: '/mimi-bio',
    emoji: '\u{1F4D6}',
    colorTheme: 'Baby Pink',
    specialHobby: 'Puzzles, Books & "Why/How" Questions',
    bio: 'Smartest kid, loves "Why" and "How" questions, solving tough puzzles with her sharp brain.',
    gemstone: 'Taaffeite',
    card: {
      color: '#fbcfe8',
      shadowDark: '#be185d',
      shadowLight: '#fce7f3',
      innerLight: '#fdf2f8',
      innerDark: '#ec4899',
      textClass: 'text-slate-900',
      pillBg: '#f9a8d4',
      pillTextClass: 'text-pink-950',
    },
  },
  {
    key: 'miko',
    name: 'Miko',
    cardTitle: 'MIKO BIO',
    route: '/miko-bio',
    emoji: '\u{1F331}',
    colorTheme: 'Light Green',
    specialHobby: 'Nature, Gardening & Earth Defense',
    bio: 'Nature-lover and Earth-defender, loves exploring plants, animals, and gardening.',
    gemstone: 'Grandidierite',
    card: {
      color: '#86efac',
      shadowDark: '#15803d',
      shadowLight: '#dcfce7',
      innerLight: '#f0fdf4',
      innerDark: '#22c55e',
      textClass: 'text-slate-900',
      pillBg: '#d9f99d',
      pillTextClass: 'text-lime-950',
    },
  },
  {
    key: 'chiko',
    name: 'Chiko',
    cardTitle: 'CHIKO BIO',
    route: '/chiko-bio',
    emoji: '\u{1F916}',
    colorTheme: 'Deep Ocean Blue',
    specialHobby: 'Gadgets, Coding & Robot Inventions',
    bio: 'Tech-genius and inventor, loves gadgets, coding, and dreaming about future technology.',
    gemstone: 'Tanzanite',
    card: {
      color: '#1e3a8a',
      shadowDark: '#172554',
      shadowLight: '#60a5fa',
      innerLight: '#93c5fd',
      innerDark: '#1d4ed8',
      textClass: 'text-white',
      pillBg: '#bfdbfe',
      pillTextClass: 'text-blue-950',
    },
  },
];

export const CHARACTER_PROFILE_BY_KEY = CHARACTER_PROFILES.reduce((accumulator, profile) => {
  accumulator[profile.key] = profile;
  return accumulator;
}, {});
