export const JUNIOR_QUIZ_REWARD_GEMS = 50;
export const JUNIOR_LAW_MILESTONE_SIZE = 10;
export const JUNIOR_LAW_MILESTONE_REWARD_GEMS = 15;

// Keep this structure for easy edits:
// {
//   id: "law-1",
//   question: "Question text",
//   options: ["Option A", "Option B", "Option C", "Option D"],
//   answer: "Exact correct option text"
// }

export const JUNIOR_LAW_QUIZ_QUESTIONS = [
  {
    id: "law-1",
    question: "What does a Red Light mean at a traffic signal?",
    options: ["Stop", "Drive faster", "Keep honking", "Turn right immediately"],
    answer: "Stop",
  },
  {
    id: "law-2",
    question: "Do children have the Right to Education in school?",
    options: ["No", "Only some children", "Yes, all children", "Only children in big cities"],
    answer: "Yes, all children",
  },
  {
    id: "law-3",
    question: "When should you use a Zebra Crossing?",
    options: ["To race bicycles", "To cross the road safely", "To park your vehicle", "To stop a bus"],
    answer: "To cross the road safely",
  },
  {
    id: "law-4",
    question: "What should you do if a stranger offers you a chocolate?",
    options: [
      "Take it and keep it secret",
      "Go with the stranger",
      "Say No and tell your parents",
      "Share it with friends",
    ],
    answer: "Say No and tell your parents",
  },
  {
    id: "law-5",
    question: "Where should you always throw garbage?",
    options: ["On the road", "Out of the window", "In the Dustbin", "In the park"],
    answer: "In the Dustbin",
  },
  {
    id: "law-6",
    question: "What is the emergency number for the Police?",
    options: ["101", "100 or 112", "108", "1098"],
    answer: "100 or 112",
  },
  {
    id: "law-7",
    question: "Is it legal for children to work in a factory?",
    options: [
      "Yes, if it is a holiday",
      "Yes, if parents allow it",
      "No, it is Child Labour and it is a crime",
      "Yes, but only on weekends",
    ],
    answer: "No, it is Child Labour and it is a crime",
  },
  {
    id: "law-8",
    question: "How should we treat our National Flag (Tiranga)?",
    options: [
      "Ignore it",
      "Use it carelessly",
      "With great respect",
      "Only click photos with it",
    ],
    answer: "With great respect",
  },
  {
    id: "law-9",
    question: "Is it okay to pluck flowers in a public park?",
    options: [
      "Yes, always",
      "No, we must protect nature",
      "Yes, only on Sundays",
      "Yes, if friends say so",
    ],
    answer: "No, we must protect nature",
  },
  {
    id: "law-10",
    question: "Is bullying or teasing other children allowed?",
    options: ["Yes, for fun", "No, we should be kind to everyone", "Only after school", "Only online"],
    answer: "No, we should be kind to everyone",
  },
  {
    id: "law-11",
    question: "Why must we give way to an Ambulance?",
    options: [
      "To reduce noise",
      "For fun",
      "To save someone's life",
      "Because traffic police said so only",
    ],
    answer: "To save someone's life",
  },
  {
    id: "law-12",
    question: "What should you do if the Fire Alarm rings at school?",
    options: [
      "Hide under your desk",
      "Stay calm and exit immediately",
      "Start recording a video",
      "Try to switch off the alarm",
    ],
    answer: "Stay calm and exit immediately",
  },
  {
    id: "law-13",
    question: "Why is it important to wear a helmet while riding?",
    options: ["For style", "For head safety", "For school rules", "Only for racing"],
    answer: "For head safety",
  },
  {
    id: "law-14",
    question: "Why are there two types of dustbins (Green and Blue)?",
    options: [
      "For decoration",
      "For school and home separately",
      "To separate wet and dry waste",
      "For big and small waste",
    ],
    answer: "To separate wet and dry waste",
  },
  {
    id: "law-15",
    question: "Which side of the road should we walk on in India?",
    options: ["Right side", "Middle of the road", "Left side", "Any side"],
    answer: "Left side",
  },
  {
    id: "law-16",
    question: "How should you stand during the National Anthem?",
    options: [
      "While talking",
      "Still and in attention",
      "Sitting down",
      "While using your phone",
    ],
    answer: "Still and in attention",
  },
  {
    id: "law-17",
    question: "Do children have the Right to Expression (to speak their mind)?",
    options: ["No", "Yes, their voice matters", "Only during exams", "Only at home"],
    answer: "Yes, their voice matters",
  },
  {
    id: "law-18",
    question: "Is it safe to touch electric switches with wet hands?",
    options: ["Yes, it is safe", "No, it is very dangerous", "Only in winter", "It does not matter"],
    answer: "No, it is very dangerous",
  },
  {
    id: "law-19",
    question: "What kind of act is stealing?",
    options: ["A smart act", "It is a bad act and a legal crime", "Okay if the item is small", "Only wrong in games"],
    answer: "It is a bad act and a legal crime",
  },
  {
    id: "law-20",
    question: "What is the Constitution?",
    options: ["A school diary", "The book of laws for the country", "A map book", "A story book"],
    answer: "The book of laws for the country",
  },
  {
    id: "law-21",
    question: "What is the purpose of a CCTV camera?",
    options: ["To play music", "To keep everyone safe", "To switch lights on and off", "To paint roads"],
    answer: "To keep everyone safe",
  },
  {
    id: "law-22",
    question: "Whom should you talk to about Good Touch and Bad Touch?",
    options: ["No one", "Only friends", "Parents or Teachers", "Online strangers"],
    answer: "Parents or Teachers",
  },
  {
    id: "law-23",
    question: "What is the job of a Judge?",
    options: [
      "To umpire cricket matches",
      "To decide what is right and wrong by law",
      "To operate traffic lights",
      "To drive school buses",
    ],
    answer: "To decide what is right and wrong by law",
  },
  {
    id: "law-24",
    question: "Is it legal to hurt animals?",
    options: ["Yes", "No, they also have the right to live safely", "Only in forests", "Only small animals"],
    answer: "No, they also have the right to live safely",
  },
  {
    id: "law-25",
    question: "Why is playing on the road forbidden?",
    options: [
      "Roads are dirty",
      "Because of the risk of accidents",
      "Because the ball can get lost",
      "Because it is sunny",
    ],
    answer: "Because of the risk of accidents",
  },
  {
    id: "law-26",
    question: "Why must we stay quiet in a hospital?",
    options: ["Doctors may scold us", "Patients need rest to recover", "The gate will close", "The TV will stop"],
    answer: "Patients need rest to recover",
  },
  {
    id: "law-27",
    question: "What is Voting for adults?",
    options: ["A hobby", "A legal right and responsibility", "Time pass", "A festival activity"],
    answer: "A legal right and responsibility",
  },
  {
    id: "law-28",
    question: "What is the use of a Lost and Found desk?",
    options: ["To sell new items", "To find missing items", "To issue tickets", "To host games"],
    answer: "To find missing items",
  },
  {
    id: "law-29",
    question: "How should you behave in a public library?",
    options: ["Talk loudly", "Read quietly and maintain silence", "Run between shelves", "Have a food party"],
    answer: "Read quietly and maintain silence",
  },
  {
    id: "law-30",
    question: "Can children start a YouTube channel?",
    options: [
      "No",
      "Only after age 18",
      "Yes, with parental permission",
      "Only if teachers allow",
    ],
    answer: "Yes, with parental permission",
  },
];

export const JUNIOR_SCIENCE_QUIZ_QUESTIONS = [
  {
    id: "science-1",
    question: "Paudhe (Plants) apna khana kaise banate hain?",
    options: ["Mitti kha kar", "Suraj ki roshni se", "Sirf paani se", "Hawa pee kar"],
    answer: "Suraj ki roshni se",
  },
  {
    id: "science-2",
    question: "Humein saans lene ke liye kaunsi gas chahiye?",
    options: ["Carbon Dioxide", "Nitrogen", "Oxygen", "Helium"],
    answer: "Oxygen",
  },
  {
    id: "science-3",
    question: "Paani ka rang kaisa hota hai?",
    options: ["Neela", "Hara", "Colorless / Koi rang nahi", "Peela"],
    answer: "Colorless / Koi rang nahi",
  },
  {
    id: "science-4",
    question: "Zameen par girne wali cheez niche hi kyu jati hai?",
    options: ["Hawa dhakelti hai", "Gravity ki wajah se", "Suraj kheechta hai", "Paani kheechta hai"],
    answer: "Gravity ki wajah se",
  },
  {
    id: "science-5",
    question: "Suraj (Sun) kya hai?",
    options: ["Ek planet", "Ek bada Tara/Star", "Ek upgrah", "Gas balloon"],
    answer: "Ek bada Tara/Star",
  },
  {
    id: "science-6",
    question: "Ek saal mein kitne mahine hote hain?",
    options: ["10", "11", "12", "13"],
    answer: "12",
  },
  {
    id: "science-7",
    question: "Barf (Ice) garam karne par kya banti hai?",
    options: ["Dhool", "Paani", "Patthar", "Dhuaan"],
    answer: "Paani",
  },
  {
    id: "science-8",
    question: "Duniya ka sabse bada janwar kaunsa hai?",
    options: ["Elephant", "Blue Whale", "Giraffe", "Hippo"],
    answer: "Blue Whale",
  },
  {
    id: "science-9",
    question: "Bijli (Electricity) kisse banti hai?",
    options: ["Sirf battery se", "Paani, Wind ya Solar se", "Sirf petrol se", "Sirf lakdi se"],
    answer: "Paani, Wind ya Solar se",
  },
  {
    id: "science-10",
    question: "Aasman neela kyu dikhta hai?",
    options: ["Clouds neela rang dete hain", "Light scattering ki wajah se", "Samundar ka rang upar jata hai", "Chand ki wajah se"],
    answer: "Light scattering ki wajah se",
  },
  {
    id: "science-11",
    question: "Hamare shareer mein kitni haddiyan (Bones) hoti hain?",
    options: ["150", "180", "206", "250"],
    answer: "206",
  },
  {
    id: "science-12",
    question: "Chand (Moon) ki apni roshni hoti hai?",
    options: ["Haan, bahut tez", "Nahi, wo Suraj se leta hai", "Sirf raat mein hoti hai", "Sirf Poornima par hoti hai"],
    answer: "Nahi, wo Suraj se leta hai",
  },
  {
    id: "science-13",
    question: "Ped humein kya dete hain?",
    options: ["Sirf chhaya", "Oxygen aur Phal", "Sirf lakdi", "Sirf patte"],
    answer: "Oxygen aur Phal",
  },
  {
    id: "science-14",
    question: "Andhera kab hota hai?",
    options: ["Jab hawa tez ho", "Jab Suraj dhal jata hai", "Jab barish aaye", "Jab chand chamke"],
    answer: "Jab Suraj dhal jata hai",
  },
  {
    id: "science-15",
    question: "Rainbow mein kitne rang hote hain?",
    options: ["5", "6", "7", "8"],
    answer: "7",
  },
  {
    id: "science-16",
    question: "Machli kaise saans leti hai?",
    options: ["Fins se", "Gills se", "Nose se", "Skin se"],
    answer: "Gills se",
  },
  {
    id: "science-17",
    question: "Sona (Gold) kahan se milta hai?",
    options: ["Nadi ke upar tairta hai", "Zameen ke niche se/Mines", "Ped par ugta hai", "Samundar ki hawa se"],
    answer: "Zameen ke niche se/Mines",
  },
  {
    id: "science-18",
    question: "Mobile phone kaise kaam karta hai?",
    options: ["Rassi se", "Signals/Waves se", "Dhuein se", "Magnet se hi"],
    answer: "Signals/Waves se",
  },
  {
    id: "science-19",
    question: "Shahad (Honey) kaun banata hai?",
    options: ["Titli", "Madhumakkhi/Honeybee", "Makdi", "Cheenti"],
    answer: "Madhumakkhi/Honeybee",
  },
  {
    id: "science-20",
    question: "Doodh peena kyu zaroori hai?",
    options: ["Sirf taste ke liye", "Haddiyon ko mazboot karne ke liye", "Sirf lamba hone ke liye", "Neend lane ke liye"],
    answer: "Haddiyon ko mazboot karne ke liye",
  },
  {
    id: "science-21",
    question: "Garmiyon mein hum kaise kapde pehente hain?",
    options: ["Woolen", "Suti/Cotton", "Raincoat", "Leather"],
    answer: "Suti/Cotton",
  },
  {
    id: "science-22",
    question: "Earth ka shape kaisa hai?",
    options: ["Flat", "Triangle", "Gool/Round", "Square"],
    answer: "Gool/Round",
  },
  {
    id: "science-23",
    question: "Taare raat mein kyu chamakte hain?",
    options: ["Wo bahut door ke suraj hain", "Street light ki wajah se", "Clouds reflect karte hain", "Chand unhe on karta hai"],
    answer: "Wo bahut door ke suraj hain",
  },
  {
    id: "science-24",
    question: "Spider ke kitne pair hote hain?",
    options: ["6", "8", "10", "12"],
    answer: "8",
  },
  {
    id: "science-25",
    question: "Kaunsa phal 'King of Fruits' hai?",
    options: ["Apple", "Banana", "Aam/Mango", "Orange"],
    answer: "Aam/Mango",
  },
  {
    id: "science-26",
    question: "Paani ubalne par kya banta hai?",
    options: ["Barf", "Bhaap/Steam", "Mitti", "Namak"],
    answer: "Bhaap/Steam",
  },
  {
    id: "science-27",
    question: "Hawa (Air) ko hum dekh sakte hain?",
    options: ["Haan, hamesha", "Nahi, sirf mehsoos kar sakte hain", "Sirf raat ko", "Sirf microscope se bina feel kiye"],
    answer: "Nahi, sirf mehsoos kar sakte hain",
  },
  {
    id: "science-28",
    question: "Barish kaise hoti hai?",
    options: ["Suraj se paani girta hai", "Baadalo se paani girne par", "Hawa tootne par", "Ped hilaane par"],
    answer: "Baadalo se paani girne par",
  },
  {
    id: "science-29",
    question: "Sabse tez daudne wala janwar kaunsa hai?",
    options: ["Horse", "Leopard", "Cheetah", "Tiger"],
    answer: "Cheetah",
  },
  {
    id: "science-30",
    question: "Humein vitamin D kahan se milta hai?",
    options: ["Chocolate se", "Dhoop se", "Cold drink se", "Mitti se"],
    answer: "Dhoop se",
  },
];
