export const JUNIOR_QUIZ_REWARD_GEMS = 50;

export const JUNIOR_LAW_MILESTONE_SIZE = 10;
export const JUNIOR_LAW_MILESTONE_REWARD_GEMS = 15;

export const JUNIOR_RIGHTS_MILESTONE_SIZE = 10;
export const JUNIOR_RIGHTS_MILESTONE_REWARD_GEMS = 15;

export const JUNIOR_SCIENCE_MILESTONE_SIZE = 10;
export const JUNIOR_SCIENCE_MILESTONE_REWARD_GEMS = 15;

export const JUNIOR_NUMBERS_MILESTONE_SIZE = 10;
export const JUNIOR_NUMBERS_MILESTONE_REWARD_GEMS = 15;

export const JUNIOR_TABLES_MILESTONE_SIZE = 10;
export const JUNIOR_TABLES_MILESTONE_REWARD_GEMS = 15;

export const JUNIOR_CALCULATOR_MILESTONE_SIZE = 10;
export const JUNIOR_CALCULATOR_MILESTONE_REWARD_GEMS = 15;

// Keep this structure for easy edits:
// {
//   id: "law-1",
//   question: "Question text",
//   options: ["Option A", "Option B", "Option C", "Option D"],
//   answer: "Exact correct option text"
// }

export const JUNIOR_LAW_QUIZ_QUESTIONS = [
  {
    id: 'law-1',
    question: 'What does a Red Light mean at a traffic signal?',
    options: ['Stop', 'Drive faster', 'Keep honking', 'Turn right immediately'],
    answer: 'Stop',
  },
  {
    id: 'law-2',
    question: 'Do children have the Right to Education in school?',
    options: ['No', 'Only some children', 'Yes, all children', 'Only children in big cities'],
    answer: 'Yes, all children',
  },
  {
    id: 'law-3',
    question: 'When should you use a Zebra Crossing?',
    options: ['To race bicycles', 'To cross the road safely', 'To park your vehicle', 'To stop a bus'],
    answer: 'To cross the road safely',
  },
  {
    id: 'law-4',
    question: 'What should you do if a stranger offers you a chocolate?',
    options: ['Take it and keep it secret', 'Go with the stranger', 'Say No and tell your parents', 'Share it with friends'],
    answer: 'Say No and tell your parents',
  },
  {
    id: 'law-5',
    question: 'Where should you always throw garbage?',
    options: ['On the road', 'Out of the window', 'In the Dustbin', 'In the park'],
    answer: 'In the Dustbin',
  },
  {
    id: 'law-6',
    question: 'What is the emergency number for the Police?',
    options: ['101', '100 or 112', '108', '1098'],
    answer: '100 or 112',
  },
  {
    id: 'law-7',
    question: 'Is it legal for children to work in a factory?',
    options: ['Yes, if it is a holiday', 'Yes, if parents allow it', 'No, it is Child Labour and it is a crime', 'Yes, but only on weekends'],
    answer: 'No, it is Child Labour and it is a crime',
  },
  {
    id: 'law-8',
    question: 'How should we treat our National Flag (Tiranga)?',
    options: ['Ignore it', 'Use it carelessly', 'With great respect', 'Only click photos with it'],
    answer: 'With great respect',
  },
  {
    id: 'law-9',
    question: 'Is it okay to pluck flowers in a public park?',
    options: ['Yes, always', 'No, we must protect nature', 'Yes, only on Sundays', 'Yes, if friends say so'],
    answer: 'No, we must protect nature',
  },
  {
    id: 'law-10',
    question: 'Is bullying or teasing other children allowed?',
    options: ['Yes, for fun', 'No, we should be kind to everyone', 'Only after school', 'Only online'],
    answer: 'No, we should be kind to everyone',
  },
  {
    id: 'law-11',
    question: 'Why must we give way to an Ambulance?',
    options: ['To reduce noise', 'For fun', "To save someone's life", 'Because traffic police said so only'],
    answer: "To save someone's life",
  },
  {
    id: 'law-12',
    question: 'What should you do if the Fire Alarm rings at school?',
    options: ['Hide under your desk', 'Stay calm and exit immediately', 'Start recording a video', 'Try to switch off the alarm'],
    answer: 'Stay calm and exit immediately',
  },
  {
    id: 'law-13',
    question: 'Why is it important to wear a helmet while riding?',
    options: ['For style', 'For head safety', 'For school rules', 'Only for racing'],
    answer: 'For head safety',
  },
  {
    id: 'law-14',
    question: 'Why are there two types of dustbins (Green and Blue)?',
    options: ['For decoration', 'For school and home separately', 'To separate wet and dry waste', 'For big and small waste'],
    answer: 'To separate wet and dry waste',
  },
  {
    id: 'law-15',
    question: 'Which side of the road should we walk on in India?',
    options: ['Right side', 'Middle of the road', 'Left side', 'Any side'],
    answer: 'Left side',
  },
  {
    id: 'law-16',
    question: 'How should you stand during the National Anthem?',
    options: ['While talking', 'Still and in attention', 'Sitting down', 'While using your phone'],
    answer: 'Still and in attention',
  },
  {
    id: 'law-17',
    question: 'Do children have the Right to Expression (to speak their mind)?',
    options: ['No', 'Yes, their voice matters', 'Only during exams', 'Only at home'],
    answer: 'Yes, their voice matters',
  },
  {
    id: 'law-18',
    question: 'Is it safe to touch electric switches with wet hands?',
    options: ['Yes, it is safe', 'No, it is very dangerous', 'Only in winter', 'It does not matter'],
    answer: 'No, it is very dangerous',
  },
  {
    id: 'law-19',
    question: 'What kind of act is stealing?',
    options: ['A smart act', 'It is a bad act and a legal crime', 'Okay if the item is small', 'Only wrong in games'],
    answer: 'It is a bad act and a legal crime',
  },
  {
    id: 'law-20',
    question: 'What is the Constitution?',
    options: ['A school diary', 'The book of laws for the country', 'A map book', 'A story book'],
    answer: 'The book of laws for the country',
  },
  {
    id: 'law-21',
    question: 'What is the purpose of a CCTV camera?',
    options: ['To play music', 'To keep everyone safe', 'To switch lights on and off', 'To paint roads'],
    answer: 'To keep everyone safe',
  },
  {
    id: 'law-22',
    question: 'Whom should you talk to about Good Touch and Bad Touch?',
    options: ['No one', 'Only friends', 'Parents or Teachers', 'Online strangers'],
    answer: 'Parents or Teachers',
  },
  {
    id: 'law-23',
    question: 'What is the job of a Judge?',
    options: ['To umpire cricket matches', 'To decide what is right and wrong by law', 'To operate traffic lights', 'To drive school buses'],
    answer: 'To decide what is right and wrong by law',
  },
  {
    id: 'law-24',
    question: 'Is it legal to hurt animals?',
    options: ['Yes', 'No, they also have the right to live safely', 'Only in forests', 'Only small animals'],
    answer: 'No, they also have the right to live safely',
  },
  {
    id: 'law-25',
    question: 'Why is playing on the road forbidden?',
    options: ['Roads are dirty', 'Because of the risk of accidents', 'Because the ball can get lost', 'Because it is sunny'],
    answer: 'Because of the risk of accidents',
  },
  {
    id: 'law-26',
    question: 'Why must we stay quiet in a hospital?',
    options: ['Doctors may scold us', 'Patients need rest to recover', 'The gate will close', 'The TV will stop'],
    answer: 'Patients need rest to recover',
  },
  {
    id: 'law-27',
    question: 'What is Voting for adults?',
    options: ['A hobby', 'A legal right and responsibility', 'Time pass', 'A festival activity'],
    answer: 'A legal right and responsibility',
  },
  {
    id: 'law-28',
    question: 'What is the use of a Lost and Found desk?',
    options: ['To sell new items', 'To find missing items', 'To issue tickets', 'To host games'],
    answer: 'To find missing items',
  },
  {
    id: 'law-29',
    question: 'How should you behave in a public library?',
    options: ['Talk loudly', 'Read quietly and maintain silence', 'Run between shelves', 'Have a food party'],
    answer: 'Read quietly and maintain silence',
  },
  {
    id: 'law-30',
    question: 'Can children start a YouTube channel?',
    options: ['No', 'Only after age 18', 'Yes, with parental permission', 'Only if teachers allow'],
    answer: 'Yes, with parental permission',
  },
  {
    id: 'law-31',
    question: 'Who is known as the Father of the Indian Constitution?',
    options: ['Mahatma Gandhi', 'Dr. B.R. Ambedkar', 'Jawaharlal Nehru', 'Sardar Patel'],
    answer: 'Dr. B.R. Ambedkar',
  },
  {
    id: 'law-32',
    question: 'What is the minimum age to vote in India?',
    options: ['16 years', '17 years', '18 years', '21 years'],
    answer: '18 years',
  },
  {
    id: 'law-33',
    question: 'Is it allowed to write on the walls of historical monuments?',
    options: ['Yes, if using chalk', 'Yes, if no one is watching', 'No, it is a crime', 'Yes, with a marker only'],
    answer: 'No, it is a crime',
  },
  {
    id: 'law-34',
    question: "What is the head of a city's municipal corporation called?",
    options: ['Governor', 'Mayor', 'Collector', 'President'],
    answer: 'Mayor',
  },
  {
    id: 'law-35',
    question: 'What is the main job of the Supreme Court?',
    options: ['To collect taxes', 'To protect the law', 'To build roads', 'To run schools'],
    answer: 'To protect the law',
  },
  {
    id: 'law-36',
    question: 'Can children be forced to work in hazardous places?',
    options: ['Yes, if they are paid', 'Yes, if parents allow', 'No, it is strictly illegal', 'Yes, during vacations'],
    answer: 'No, it is strictly illegal',
  },
  {
    id: 'law-37',
    question: 'What does the blue wheel in the center of the Indian flag represent?',
    options: ['Victory', 'Peace', 'Dharma Chakra', 'Unity'],
    answer: 'Dharma Chakra',
  },
  {
    id: 'law-38',
    question: 'Is it legal to use a plastic bag if it is banned?',
    options: ['Yes, if reused', 'Yes, for shopping only', 'No, it is against the law', 'Yes, in small markets'],
    answer: 'No, it is against the law',
  },
  {
    id: 'law-39',
    question: 'What should you do if you find a lost wallet?',
    options: ['Keep it', 'Give it to a friend', 'Hand it over to the police', 'Throw it away'],
    answer: 'Hand it over to the police',
  },
  {
    id: 'law-40',
    question: "Do we have the 'Right to Equality'?",
    options: ['No', 'Only adults have it', 'Yes, everyone is equal before the law', 'Only rich people have it'],
    answer: 'Yes, everyone is equal before the law',
  },
  {
    id: 'law-41',
    question: 'What is the full form of FIR?',
    options: ['First Incident Record', 'Final Investigation Report', 'First Information Report', 'File Inspection Record'],
    answer: 'First Information Report',
  },
  {
    id: 'law-42',
    question: 'Who makes the laws for the whole country?',
    options: ['Municipal Corporation', 'Supreme Court', 'Parliament', 'Police Department'],
    answer: 'Parliament',
  },
  {
    id: 'law-43',
    question: 'Is it okay to use loud crackers late at night?',
    options: ['Yes, anytime', 'Yes, on weekends', 'No, it causes noise pollution', 'Yes, near highways'],
    answer: 'No, it causes noise pollution',
  },
  {
    id: 'law-44',
    question: "What is the 'Right to Information' (RTI)?",
    options: ['Right to own land', 'Right to ask for info from the government', 'Right to skip taxes', 'Right to vote at 16'],
    answer: 'Right to ask for info from the government',
  },
  {
    id: 'law-45',
    question: 'Can anyone be arrested without a reason?',
    options: ['Yes', 'No, there must be a legal reason', 'Yes, if police are busy', 'Only at night'],
    answer: 'No, there must be a legal reason',
  },
  {
    id: 'law-46',
    question: "What is a 'Cyber Crime'?",
    options: ['A crime in a market', 'A crime done using the internet or computers', 'A traffic violation', 'A school offense'],
    answer: 'A crime done using the internet or computers',
  },
  {
    id: 'law-47',
    question: 'Is it mandatory to wear a seatbelt in a car?',
    options: ['No', 'Yes, for safety and law', 'Only for drivers', 'Only on highways'],
    answer: 'Yes, for safety and law',
  },
  {
    id: 'law-48',
    question: "What is the 'Preamble' of the Constitution?",
    options: ['A punishment list', 'The introduction to the laws', 'A voting list', 'A police notice'],
    answer: 'The introduction to the laws',
  },
  {
    id: 'law-49',
    question: 'Can children under 14 work in tea stalls?',
    options: ['Yes', 'Only on holidays', 'No, it is child labour', 'Only with family permission'],
    answer: 'No, it is child labour',
  },
  {
    id: 'law-50',
    question: "What is the 'Right against Exploitation'?",
    options: ['Right to own property', 'Right to not be treated unfairly', 'Right to skip school', 'Right to free transport'],
    answer: 'Right to not be treated unfairly',
  },
  {
    id: 'law-51',
    question: 'Who is the head of a state government?',
    options: ['Prime Minister', 'Governor', 'Chief Minister', 'Mayor'],
    answer: 'Chief Minister',
  },
  {
    id: 'law-52',
    question: "What is the 'Rule of Law'?",
    options: ['Police can decide anything', 'Law is supreme for everyone', 'Only judges follow law', 'Only leaders follow law'],
    answer: 'Law is supreme for everyone',
  },
  {
    id: 'law-53',
    question: 'Is it legal to drive a vehicle without a license?',
    options: ['Yes, for short distance', 'No, it is a crime', 'Yes, if with parents', 'Only in villages'],
    answer: 'No, it is a crime',
  },
  {
    id: 'law-54',
    question: 'What do we call the person who fights a case in court?',
    options: ['Doctor', 'Lawyer/Advocate', 'Engineer', 'Teacher'],
    answer: 'Lawyer/Advocate',
    acceptedAnswers: ['Lawyer', 'Advocate'],
  },
  {
    id: 'law-55',
    question: 'Is education free for children in government schools?',
    options: ['No', 'Yes, up to age 14', 'Only till age 10', 'Only for boys'],
    answer: 'Yes, up to age 14',
  },
  {
    id: 'law-56',
    question: "What is 'Human Rights Day' celebrated for?",
    options: ['To celebrate sports', "To protect everyone's dignity", 'To celebrate elections', 'To celebrate money'],
    answer: "To protect everyone's dignity",
  },
  {
    id: 'law-57',
    question: 'Can you be punished twice for the same crime?',
    options: ['Yes', 'No, according to the law', 'Only in big crimes', 'Only by police'],
    answer: 'No, according to the law',
  },
  {
    id: 'law-58',
    question: "What is a 'Warrant'?",
    options: ['A school ID card', 'A legal paper to search or arrest', 'A tax form', 'A passport'],
    answer: 'A legal paper to search or arrest',
  },
  {
    id: 'law-59',
    question: 'Is it allowed to cut trees in a forest without permission?',
    options: ['Yes', 'Only in summer', 'No, it is illegal', 'Only if the tree is small'],
    answer: 'No, it is illegal',
  },
  {
    id: 'law-60',
    question: "What is the 'Right to Freedom of Religion'?",
    options: ['Right to avoid school', 'Right to follow any religion', 'Right to avoid taxes', 'Right to skip laws'],
    answer: 'Right to follow any religion',
  },
  {
    id: 'law-61',
    question: 'What is Lok Sabha?',
    options: ['Upper house of Parliament', 'Lower house of Parliament', 'State court', 'City council'],
    answer: 'Lower house of Parliament',
  },
  {
    id: 'law-62',
    question: 'What is Rajya Sabha?',
    options: ['Lower house of Parliament', 'Upper house of Parliament', 'High Court bench', 'Village council'],
    answer: 'Upper house of Parliament',
  },
  {
    id: 'law-63',
    question: 'Who is known as the first citizen of India?',
    options: ['Prime Minister', 'President of India', 'Chief Justice', 'Governor'],
    answer: 'President of India',
  },
  {
    id: 'law-64',
    question: 'What is PIL?',
    options: ['Public Identity License', 'Public Interest Litigation', 'Private Investigation Law', 'Police Information Letter'],
    answer: 'Public Interest Litigation',
  },
  {
    id: 'law-65',
    question: 'Is giving or taking a bribe legal?',
    options: ['Yes', 'No', 'Only in business', 'Only in emergencies'],
    answer: 'No',
  },
  {
    id: 'law-66',
    question: 'What should you do first if you see a road accident?',
    options: ['Record a video', 'Walk away', 'Call emergency services and help safely', 'Argue with drivers'],
    answer: 'Call emergency services and help safely',
  },
  {
    id: 'law-67',
    question: 'What is legal aid?',
    options: ['Paid legal advice only', 'Free legal help for those who cannot afford it', 'A police reward', 'A tax scheme'],
    answer: 'Free legal help for those who cannot afford it',
  },
  {
    id: 'law-68',
    question: 'Can a minor sign all legal contracts alone?',
    options: ['Yes', 'No, usually a guardian is needed', 'Only online', 'Only in school'],
    answer: 'No, usually a guardian is needed',
  },
  {
    id: 'law-69',
    question: 'What is public property?',
    options: ['Private home items', 'Property owned by government for everyone', 'Only school books', 'Personal vehicles'],
    answer: 'Property owned by government for everyone',
  },
  {
    id: 'law-70',
    question: 'Is damaging public property punishable?',
    options: ['No', 'Yes, it is an offense', 'Only in big cities', 'Only if reported by media'],
    answer: 'Yes, it is an offense',
  },
  {
    id: 'law-71',
    question: 'What is a traffic challan?',
    options: ['A driving badge', 'An official notice of fine for rule violation', 'A fuel bill', 'A parking permit'],
    answer: 'An official notice of fine for rule violation',
  },
  {
    id: 'law-72',
    question: 'What does a bailable offense mean?',
    options: ['No punishment', 'Can be released on bail', 'No court hearing', 'Only a warning'],
    answer: 'Can be released on bail',
  },
  {
    id: 'law-73',
    question: 'Can police search a home without legal authority in normal situations?',
    options: ['Yes, always', 'No, legal authority is required', 'Only in daytime', 'Only in villages'],
    answer: 'No, legal authority is required',
  },
  {
    id: 'law-74',
    question: 'What is consumer court used for?',
    options: ['Criminal trials only', 'Resolving consumer complaints', 'School disputes', 'Election disputes'],
    answer: 'Resolving consumer complaints',
  },
  {
    id: 'law-75',
    question: 'What is e-waste?',
    options: ['Food waste', 'Discarded electronic waste', 'Paper waste only', 'Plastic toys only'],
    answer: 'Discarded electronic waste',
  },
  {
    id: 'law-76',
    question: 'Can sharing someone personal data without consent be a legal issue?',
    options: ['No', 'Yes', 'Only for adults', 'Only on weekends'],
    answer: 'Yes',
  },
  {
    id: 'law-77',
    question: 'What does the juvenile justice system deal with?',
    options: ['Only property tax', 'Children in conflict with law', 'Road construction', 'Banking disputes'],
    answer: 'Children in conflict with law',
  },
  {
    id: 'law-78',
    question: 'What is a fundamental duty?',
    options: ['A hobby', 'A responsibility every citizen should follow', 'A private right', 'A school holiday'],
    answer: 'A responsibility every citizen should follow',
  },
  {
    id: 'law-79',
    question: 'Why should cyberbullying be reported?',
    options: ['To increase followers', 'To stop abuse and seek legal help', 'To make it viral', 'To ignore it'],
    answer: 'To stop abuse and seek legal help',
  },
  {
    id: 'law-80',
    question: 'What is the main aim of law in society?',
    options: ['To create fear', 'To maintain order and protect rights', 'To stop all fun', 'To reduce school time'],
    answer: 'To maintain order and protect rights',
  },
  {
    id: 'law-81',
    question: 'What is the official residence of the President of India called?',
    options: ['Rashtrapati Bhavan', 'Parliament House', 'Raj Bhavan', 'South Block'],
    answer: 'Rashtrapati Bhavan',
  },
  {
    id: 'law-82',
    question: 'Can a police officer arrest a woman after sunset without a special order?',
    options: ['Yes, always', 'No, it is protected by law', 'Yes, if there is traffic', 'Only on weekends'],
    answer: 'No, it is protected by law',
  },
  {
    id: 'law-83',
    question: "What is the 'Right to Privacy'?",
    options: ['Right to free transport', 'The right to keep your personal life private', 'Right to skip school', 'Right to own a vehicle'],
    answer: 'The right to keep your personal life private',
  },
  {
    id: 'law-84',
    question: 'Who is the supreme commander of the Indian Armed Forces?',
    options: ['The Prime Minister', 'The Home Minister', 'The President', 'The Chief of Army Staff'],
    answer: 'The President',
  },
  {
    id: 'law-85',
    question: "What is 'Child Helpline Number' in India?",
    options: ['100', '101', '1098', '112'],
    answer: '1098',
  },
  {
    id: 'law-86',
    question: 'Is it legal to buy or sell wild animals?',
    options: ['Yes, with friends', 'No, it is a crime against wildlife', 'Yes, in small markets', 'Only in villages'],
    answer: 'No, it is a crime against wildlife',
  },
  {
    id: 'law-87',
    question: "What is the 'Lokpal'?",
    options: ['A traffic police officer', 'An officer who investigates corruption', 'A school principal', 'A district judge'],
    answer: 'An officer who investigates corruption',
  },
  {
    id: 'law-88',
    question: 'Can you change your religion by your own choice?',
    options: ['No, never', 'Yes, it is a fundamental right', 'Only after 50 years', 'Only with police permission'],
    answer: 'Yes, it is a fundamental right',
  },
  {
    id: 'law-89',
    question: "What is a 'Public Interest Litigation' (PIL)?",
    options: ['A case filed for the benefit of the public', 'A private business contract', 'A school transfer letter', 'A tax payment notice'],
    answer: 'A case filed for the benefit of the public',
    acceptedAnswers: ['Public Interest Litigation', 'PIL'],
  },
  {
    id: 'law-90',
    question: "Is it mandatory to have an 'Aadhaar Card' for certain govt services?",
    options: ['No, never required', 'Yes, it is used for identification', 'Only for children', 'Only for tourists'],
    answer: 'Yes, it is used for identification',
  },
  {
    id: 'law-91',
    question: "What is the 'Juvenile Justice Act'?",
    options: ['Law for only adults', 'Special laws for children under 18', 'Rules for traffic police', 'Law for banks'],
    answer: 'Special laws for children under 18',
  },
  {
    id: 'law-92',
    question: 'Who appoints the Chief Justice of India?',
    options: ['The Parliament', 'The Prime Minister', 'The President', 'The Supreme Court Registry'],
    answer: 'The President',
  },
  {
    id: 'law-93',
    question: "What is the 'Right to Social Security'?",
    options: ['Support from the govt during old age or sickness', 'Right to own a school', 'Right to avoid taxes', 'Support only during festivals'],
    answer: 'Support from the govt during old age or sickness',
  },
  {
    id: 'law-94',
    question: 'Is child marriage legal in India?',
    options: ['Yes, with family permission', 'No, it is a punishable crime', 'Yes, in rural areas', 'Only in emergencies'],
    answer: 'No, it is a punishable crime',
  },
  {
    id: 'law-95',
    question: "What is the 'Blue Book' in Indian security?",
    options: ['A school attendance register', 'Rules for protecting VVIPs', 'A tax rule book', 'A law exam guide'],
    answer: 'Rules for protecting VVIPs',
  },
  {
    id: 'law-96',
    question: 'Can the Parliament change the Constitution?',
    options: ['No, never', 'Yes, but not its basic structure', 'Only during elections', 'Only state governments can do this'],
    answer: 'Yes, but not its basic structure',
  },
  {
    id: 'law-97',
    question: "What is 'Defamation'?",
    options: ['Damaging someone\'s reputation by lying', 'Helping people in court', 'A type of national holiday', 'A school punishment'],
    answer: "Damaging someone's reputation by lying",
  },
  {
    id: 'law-98',
    question: "Who is an 'NRI'?",
    options: ['National Road Inspector', 'Non-Resident Indian living abroad', 'New Resident of India', 'National Rights Investigator'],
    answer: 'Non-Resident Indian living abroad',
    acceptedAnswers: ['NRI', 'Non Resident Indian living abroad', 'Non Resident Indian'],
  },
  {
    id: 'law-99',
    question: "What is the 'National Green Tribunal' (NGT)?",
    options: ['A court for environmental cases', 'A sports committee', 'A school science club', 'A traffic control room'],
    answer: 'A court for environmental cases',
    acceptedAnswers: ['National Green Tribunal', 'NGT'],
  },
  {
    id: 'law-100',
    question: 'Is it legal to use a phone while driving?',
    options: ['Yes, if traffic is slow', 'No, it is a dangerous traffic violation', 'Only for short calls', 'Yes, with headphones'],
    answer: 'No, it is a dangerous traffic violation',
  },
];

export const JUNIOR_RIGHTS_QUIZ_QUESTIONS = [
  {
    id: 'rights-1',
    question: 'Do all children have a right to go to school?',
    options: ['Yes', 'No', 'Only in cities', 'Only after age 10'],
    answer: 'Yes',
  },
  {
    id: 'rights-2',
    question: 'Which right helps children learn reading and math?',
    options: ['Right to Property', 'Right to Education', 'Right to Vote', 'Right to Drive'],
    answer: 'Right to Education',
  },
  {
    id: 'rights-3',
    question: 'Is it okay to stop a child from school because the family is poor?',
    options: ['Yes', 'No', 'Only sometimes', 'Only for boys'],
    answer: 'No',
  },
  {
    id: 'rights-4',
    question: 'Should children get time to play every day?',
    options: ['Yes', 'No', 'Only on Sundays', 'Only after exams'],
    answer: 'Yes',
  },
  {
    id: 'rights-5',
    question: 'Which place lets children read many books?',
    options: ['Factory', 'Library', 'Parking lot', 'Cinema hall'],
    answer: 'Library',
  },
  {
    id: 'rights-6',
    question: 'Can both girls and boys go to school?',
    options: ['Yes', 'No', 'Only in private schools', 'Only in colleges'],
    answer: 'Yes',
  },
  {
    id: 'rights-7',
    question: 'Is regular school attendance important for learning?',
    options: ['Yes', 'No', 'Only for sports', 'Only for homework'],
    answer: 'Yes',
  },
  {
    id: 'rights-8',
    question: 'Who mainly helps children learn in school?',
    options: ['Teacher', 'Shopkeeper', 'Driver', 'Chef'],
    answer: 'Teacher',
  },
  {
    id: 'rights-9',
    question: 'Do children have a right to rest and leisure?',
    options: ['Yes', 'No', 'Only adults do', 'Only in summer'],
    answer: 'Yes',
  },
  {
    id: 'rights-10',
    question: 'Which activity helps children practice learning at home?',
    options: ['Homework', 'Skipping meals', 'Fighting', 'Littering'],
    answer: 'Homework',
  },
  {
    id: 'rights-11',
    question: 'Is it right to force a child to work instead of studying?',
    options: ['Yes', 'No', 'Only in holidays', 'Only at family shops'],
    answer: 'No',
  },
  {
    id: 'rights-12',
    question: 'What should every school provide to children?',
    options: ['Unsafe rooms', 'Safe learning space', 'Only exams', 'No playground'],
    answer: 'Safe learning space',
  },
  {
    id: 'rights-13',
    question: 'Can a child ask for help if a lesson is difficult?',
    options: ['Yes', 'No', 'Only toppers can', 'Only on test day'],
    answer: 'Yes',
  },
  {
    id: 'rights-14',
    question: 'Should children be allowed to join school activities?',
    options: ['Yes', 'No', 'Only seniors', 'Only teachers'],
    answer: 'Yes',
  },
  {
    id: 'rights-15',
    question: 'Should playgrounds be safe for children?',
    options: ['Yes', 'No', 'Only for adults', 'Only on weekends'],
    answer: 'Yes',
  },
  {
    id: 'rights-16',
    question: 'Which right supports fair school admission?',
    options: ['Right to Education', 'Right to Traffic', 'Right to Tax', 'Right to Weather'],
    answer: 'Right to Education',
  },
  {
    id: 'rights-17',
    question: 'Do children have a right to clean drinking water in school?',
    options: ['Yes', 'No', 'Only in summer', 'Only in hostels'],
    answer: 'Yes',
  },
  {
    id: 'rights-18',
    question: 'Is reading storybooks useful for learning?',
    options: ['Yes', 'No', 'Never', 'Only for adults'],
    answer: 'Yes',
  },
  {
    id: 'rights-19',
    question: 'Can children with disabilities also attend school?',
    options: ['Yes', 'No', 'Only private schools', 'Only online'],
    answer: 'Yes',
  },
  {
    id: 'rights-20',
    question: 'What is a quiet place to study and read?',
    options: ['Library', 'Highway', 'Market', 'Playground'],
    answer: 'Library',
  },
  {
    id: 'rights-21',
    question: 'Should parents encourage children to attend school daily?',
    options: ['Yes', 'No', 'Only before exams', 'Only on Mondays'],
    answer: 'Yes',
  },
  {
    id: 'rights-22',
    question: 'Is online learning also a form of education?',
    options: ['Yes', 'No', 'Only games', 'Only for college'],
    answer: 'Yes',
  },
  {
    id: 'rights-23',
    question: 'Do children have a right to ask questions in class?',
    options: ['Yes', 'No', 'Only class monitor', 'Only after school'],
    answer: 'Yes',
  },
  {
    id: 'rights-24',
    question: 'Which right protects time for games and sports?',
    options: ['Right to Play', 'Right to Drive', 'Right to Tax', 'Right to Arrest'],
    answer: 'Right to Play',
  },
  {
    id: 'rights-25',
    question: 'Is school also a place for friendship and social learning?',
    options: ['Yes', 'No', 'Only for marks', 'Only for attendance'],
    answer: 'Yes',
  },
  {
    id: 'rights-26',
    question: 'What is the Child Helpline number in India?',
    options: ['100', '101', '1098', '1120'],
    answer: '1098',
  },
  {
    id: 'rights-27',
    question: 'What should a child do after a bad touch experience?',
    options: ['Stay silent', 'Tell a trusted adult', 'Run away forever', 'Delete chats only'],
    answer: 'Tell a trusted adult',
  },
  {
    id: 'rights-28',
    question: 'Is bullying allowed in school?',
    options: ['Yes', 'No', 'Only in games', 'Only online'],
    answer: 'No',
  },
  {
    id: 'rights-29',
    question: 'Whom should children talk to about good touch and bad touch?',
    options: ['Strangers', 'Parents or Teachers', 'No one', 'Only classmates'],
    answer: 'Parents or Teachers',
  },
  {
    id: 'rights-30',
    question: 'Should personal body boundaries be respected?',
    options: ['Yes', 'No', 'Only at home', 'Only at school'],
    answer: 'Yes',
  },
  {
    id: 'rights-31',
    question: 'Is it safe to share your home address with strangers online?',
    options: ['Yes', 'No', 'Only once', 'Only with gamers'],
    answer: 'No',
  },
  {
    id: 'rights-32',
    question: 'What should a child do if someone threatens them?',
    options: ['Ignore forever', 'Tell a trusted adult', 'Pay money', 'Keep secret'],
    answer: 'Tell a trusted adult',
  },
  {
    id: 'rights-33',
    question: 'Should children stay with known adults in crowded places?',
    options: ['Yes', 'No', 'Only in malls', 'Only in parks'],
    answer: 'Yes',
  },
  {
    id: 'rights-34',
    question: 'Can a child call 1098 if they feel unsafe?',
    options: ['Yes', 'No', 'Only at night', 'Only with permission from strangers'],
    answer: 'Yes',
  },
  {
    id: 'rights-35',
    question: 'Is hitting a child acceptable discipline?',
    options: ['Yes', 'No', 'Only in school', 'Only for homework'],
    answer: 'No',
  },
  {
    id: 'rights-36',
    question: 'If lost in a market, whom should a child approach?',
    options: ['Random stranger', 'Police or a help desk', 'No one', 'Another child only'],
    answer: 'Police or a help desk',
  },
  {
    id: 'rights-37',
    question: 'Should schools have anti-bullying rules?',
    options: ['Yes', 'No', 'Only in big schools', 'Only for seniors'],
    answer: 'Yes',
  },
  {
    id: 'rights-38',
    question: 'Is it okay to keep bad touch a secret from parents?',
    options: ['Yes', 'No', 'Only if scared', 'Only for one day'],
    answer: 'No',
  },
  {
    id: 'rights-39',
    question: 'Who helps protect children by law?',
    options: ['Police and child protection services', 'Only neighbors', 'Only friends', 'No one'],
    answer: 'Police and child protection services',
  },
  {
    id: 'rights-40',
    question: 'Should children wear a seat belt in a car?',
    options: ['Yes', 'No', 'Only on highways', 'Only in front seat'],
    answer: 'Yes',
  },
  {
    id: 'rights-41',
    question: 'Is cyberbullying a serious safety issue?',
    options: ['Yes', 'No', 'Only for adults', 'Only in games'],
    answer: 'Yes',
  },
  {
    id: 'rights-42',
    question: 'What should you do if a friend is being bullied?',
    options: ['Laugh', 'Help and report to an adult', 'Ignore', 'Record and share'],
    answer: 'Help and report to an adult',
  },
  {
    id: 'rights-43',
    question: 'Should parents know who children chat with online?',
    options: ['Yes', 'No', 'Only on weekends', 'Only if phone is old'],
    answer: 'Yes',
  },
  {
    id: 'rights-44',
    question: 'Is it safe to meet an online stranger alone?',
    options: ['Yes', 'No', 'Only in malls', 'Only in daytime'],
    answer: 'No',
  },
  {
    id: 'rights-45',
    question: 'Which number is commonly used for police emergency in India?',
    options: ['1098', '102', '112', '1088'],
    answer: '112',
    acceptedAnswers: ['100'],
  },
  {
    id: 'rights-46',
    question: 'Is child marriage harmful and illegal?',
    options: ['Yes', 'No', 'Only in cities', 'Only for boys'],
    answer: 'Yes',
  },
  {
    id: 'rights-47',
    question: 'Should schools teach good touch and bad touch safety?',
    options: ['Yes', 'No', 'Only in high school', 'Only online'],
    answer: 'Yes',
  },
  {
    id: 'rights-48',
    question: 'Can teachers and parents create a safety plan for children?',
    options: ['Yes', 'No', 'Only police can', 'Only doctors can'],
    answer: 'Yes',
  },
  {
    id: 'rights-49',
    question: 'Is locking a child alone as punishment safe?',
    options: ['Yes', 'No', 'Only for one hour', 'Only in school'],
    answer: 'No',
  },
  {
    id: 'rights-50',
    question: 'What is the first step during a school emergency?',
    options: ['Run anywhere', 'Inform a teacher immediately', 'Hide phone', 'Post online'],
    answer: 'Inform a teacher immediately',
  },
  {
    id: 'rights-51',
    question: 'Does every child have a right to a name?',
    options: ['Yes', 'No', 'Only after 10 years', 'Only with passport'],
    answer: 'Yes',
  },
  {
    id: 'rights-52',
    question: 'Does every child have a right to a nationality?',
    options: ['Yes', 'No', 'Only adults do', 'Only in cities'],
    answer: 'Yes',
  },
  {
    id: 'rights-53',
    question: 'Should children be treated equally regardless religion?',
    options: ['Yes', 'No', 'Only in school', 'Only in parks'],
    answer: 'Yes',
  },
  {
    id: 'rights-54',
    question: 'Is discrimination by caste or skin color allowed?',
    options: ['Yes', 'No', 'Only in sports', 'Only online'],
    answer: 'No',
  },
  {
    id: 'rights-55',
    question: 'Can children with disabilities enjoy the same rights?',
    options: ['Yes', 'No', 'Only some rights', 'Only at home'],
    answer: 'Yes',
  },
  {
    id: 'rights-56',
    question: 'Which document records a child birth identity?',
    options: ['Movie ticket', 'Birth Certificate', 'Bus pass', 'Library card'],
    answer: 'Birth Certificate',
  },
  {
    id: 'rights-57',
    question: 'Is teasing someone for their language fair?',
    options: ['Yes', 'No', 'Only for fun', 'Only in class'],
    answer: 'No',
  },
  {
    id: 'rights-58',
    question: 'Should girls and boys get equal opportunities?',
    options: ['Yes', 'No', 'Only in sports', 'Only in exams'],
    answer: 'Yes',
  },
  {
    id: 'rights-59',
    question: 'Can children keep their own culture and traditions?',
    options: ['Yes', 'No', 'Only adults can', 'Only on festivals'],
    answer: 'Yes',
  },
  {
    id: 'rights-60',
    question: 'Is it okay to deny schooling because of disability?',
    options: ['Yes', 'No', 'Only in small schools', 'Only if classes are full'],
    answer: 'No',
  },
  {
    id: 'rights-61',
    question: 'Which right says everyone is equal before the law?',
    options: ['Right to Equality', 'Right to Property', 'Right to Tax', 'Right to Drive'],
    answer: 'Right to Equality',
  },
  {
    id: 'rights-62',
    question: 'Should schools welcome children from every background?',
    options: ['Yes', 'No', 'Only top scorers', 'Only local children'],
    answer: 'Yes',
  },
  {
    id: 'rights-63',
    question: 'Is mocking someone accent respectful?',
    options: ['Yes', 'No', 'Sometimes', 'Only online'],
    answer: 'No',
  },
  {
    id: 'rights-64',
    question: 'Do adopted children also have full rights?',
    options: ['Yes', 'No', 'Only education right', 'Only play right'],
    answer: 'Yes',
  },
  {
    id: 'rights-65',
    question: 'What helps prove a child legal identity early in life?',
    options: ['Birth Certificate', 'Game ID', 'Shopping bill', 'TV ticket'],
    answer: 'Birth Certificate',
  },
  {
    id: 'rights-66',
    question: 'Can a child be excluded from school for being poor?',
    options: ['Yes', 'No', 'Only in private schools', 'Only in towns'],
    answer: 'No',
  },
  {
    id: 'rights-67',
    question: 'Should classrooms include children with special needs?',
    options: ['Yes', 'No', 'Only separate schools', 'Only online classes'],
    answer: 'Yes',
  },
  {
    id: 'rights-68',
    question: 'Is insulting someone religion acceptable?',
    options: ['Yes', 'No', 'Only in jokes', 'Only in sports'],
    answer: 'No',
  },
  {
    id: 'rights-69',
    question: 'Can children speak their mother tongue at home?',
    options: ['Yes', 'No', 'Only holidays', 'Only if parents allow schools'],
    answer: 'Yes',
  },
  {
    id: 'rights-70',
    question: 'Do refugee children also deserve protection and education?',
    options: ['Yes', 'No', 'Only adults do', 'Only rich children'],
    answer: 'Yes',
  },
  {
    id: 'rights-71',
    question: 'Is using someone personal identity details without permission okay?',
    options: ['Yes', 'No', 'Only once', 'Only with friends'],
    answer: 'No',
  },
  {
    id: 'rights-72',
    question: 'Can a child follow family faith and traditions peacefully?',
    options: ['Yes', 'No', 'Only after 18', 'Only in cities'],
    answer: 'Yes',
  },
  {
    id: 'rights-73',
    question: 'Should every child be registered in birth records?',
    options: ['Yes', 'No', 'Only boys', 'Only in private hospitals'],
    answer: 'Yes',
  },
  {
    id: 'rights-74',
    question: 'Is fairness connected with dignity for all children?',
    options: ['Yes', 'No', 'Only in school', 'Only in courts'],
    answer: 'Yes',
  },
  {
    id: 'rights-75',
    question: 'Which right protects children from unfair discrimination?',
    options: ['Right to Equality', 'Right to Tax', 'Right to Parking', 'Right to Fuel'],
    answer: 'Right to Equality',
  },
  {
    id: 'rights-76',
    question: 'Do children have a right to express opinions respectfully?',
    options: ['Yes', 'No', 'Only adults can', 'Only online'],
    answer: 'Yes',
  },
  {
    id: 'rights-77',
    question: 'Can children ask questions to parents and teachers?',
    options: ['Yes', 'No', 'Only in exams', 'Only at home'],
    answer: 'Yes',
  },
  {
    id: 'rights-78',
    question: 'Is listening to children views important?',
    options: ['Yes', 'No', 'Only for seniors', 'Only in debates'],
    answer: 'Yes',
  },
  {
    id: 'rights-79',
    question: 'Should school councils include children voices?',
    options: ['Yes', 'No', 'Only teachers', 'Only principals'],
    answer: 'Yes',
  },
  {
    id: 'rights-80',
    question: 'Can a child say no to unsafe requests?',
    options: ['Yes', 'No', 'Only at school', 'Only with parents'],
    answer: 'Yes',
  },
  {
    id: 'rights-81',
    question: 'Is peaceful participation in school activities allowed?',
    options: ['Yes', 'No', 'Only toppers', 'Only sports captains'],
    answer: 'Yes',
  },
  {
    id: 'rights-82',
    question: 'Should adults explain decisions that affect children?',
    options: ['Yes', 'No', 'Only after exams', 'Only in cities'],
    answer: 'Yes',
  },
  {
    id: 'rights-83',
    question: 'Can children share ideas through drawing, writing, or speaking?',
    options: ['Yes', 'No', 'Only drawing allowed', 'Only speaking allowed'],
    answer: 'Yes',
  },
  {
    id: 'rights-84',
    question: 'Is it okay to silence a child all the time?',
    options: ['Yes', 'No', 'Only in class', 'Only at home'],
    answer: 'No',
  },
  {
    id: 'rights-85',
    question: 'Which right says children should be heard in matters affecting them?',
    options: ['Right to Participation', 'Right to Fuel', 'Right to Parking', 'Right to Tax'],
    answer: 'Right to Participation',
  },
  {
    id: 'rights-86',
    question: 'Can children report unfair treatment at school?',
    options: ['Yes', 'No', 'Only monitor can', 'Only parents can'],
    answer: 'Yes',
  },
  {
    id: 'rights-87',
    question: 'Should children be free to choose hobbies?',
    options: ['Yes', 'No', 'Only sports', 'Only music'],
    answer: 'Yes',
  },
  {
    id: 'rights-88',
    question: 'Is respectful debate in class good for learning?',
    options: ['Yes', 'No', 'Never', 'Only once a year'],
    answer: 'Yes',
  },
  {
    id: 'rights-89',
    question: 'Can children join school clubs and teams?',
    options: ['Yes', 'No', 'Only seniors', 'Only weekdays'],
    answer: 'Yes',
  },
  {
    id: 'rights-90',
    question: 'Should school rules improve using children feedback?',
    options: ['Yes', 'No', 'Only principal decides', 'Only after exams'],
    answer: 'Yes',
  },
  {
    id: 'rights-91',
    question: 'Is hate speech protected as a child right?',
    options: ['Yes', 'No', 'Only online', 'Only in private chats'],
    answer: 'No',
  },
  {
    id: 'rights-92',
    question: 'Can children join community clean-up with adult guidance?',
    options: ['Yes', 'No', 'Only adults', 'Only on TV'],
    answer: 'Yes',
  },
  {
    id: 'rights-93',
    question: 'Should a child be punished for asking a genuine question?',
    options: ['Yes', 'No', 'Only in math class', 'Only in exams'],
    answer: 'No',
  },
  {
    id: 'rights-94',
    question: 'Do children have a right to age-appropriate information?',
    options: ['Yes', 'No', 'Only adults do', 'Only in libraries'],
    answer: 'Yes',
  },
  {
    id: 'rights-95',
    question: 'Can children express feelings through art and music?',
    options: ['Yes', 'No', 'Only art', 'Only music'],
    answer: 'Yes',
  },
  {
    id: 'rights-96',
    question: 'Is it good for children to discuss problems with trusted adults?',
    options: ['Yes', 'No', 'Only friends', 'Only online'],
    answer: 'Yes',
  },
  {
    id: 'rights-97',
    question: 'Can children suggest ideas for safer schools?',
    options: ['Yes', 'No', 'Only teachers can', 'Only police can'],
    answer: 'Yes',
  },
  {
    id: 'rights-98',
    question: 'Should children be heard in family decisions affecting them?',
    options: ['Yes', 'No', 'Only adults decide', 'Only at festivals'],
    answer: 'Yes',
  },
  {
    id: 'rights-99',
    question: 'Is respectful disagreement allowed?',
    options: ['Yes', 'No', 'Only in debates', 'Only online'],
    answer: 'Yes',
  },
  {
    id: 'rights-100',
    question: 'Which right gives children freedom to share thoughts responsibly?',
    options: ['Right to Expression', 'Right to Parking', 'Right to Fuel', 'Right to Tax'],
    answer: 'Right to Expression',
  },
];

export const JUNIOR_SCIENCE_QUIZ_QUESTIONS = [
  {
    id: 'science-1',
    question: 'Which planet is known as the Red Planet?',
    options: ['Mars', 'Venus', 'Jupiter', 'Mercury'],
    answer: 'Mars',
  },
  {
    id: 'science-2',
    question: 'What is the freezing point of water?',
    options: ['0C', '100C', '10C', '-10C'],
    answer: '0C',
    acceptedAnswers: ['0°C', '0 C', '0 degree celsius', '0 degrees celsius'],
  },
  {
    id: 'science-3',
    question: 'Which part of the plant is under the ground?',
    options: ['Leaves', 'Flowers', 'Roots', 'Stem'],
    answer: 'Roots',
  },
  {
    id: 'science-4',
    question: 'How many legs does a spider have?',
    options: ['6', '8', '10', '12'],
    answer: '8',
  },
  {
    id: 'science-5',
    question: 'What do we call a scientist who studies stars?',
    options: ['Biologist', 'Chemist', 'Astronomer', 'Geologist'],
    answer: 'Astronomer',
  },
  {
    id: 'science-6',
    question: 'Which force pulls everything toward the Earth?',
    options: ['Magnetism', 'Friction', 'Gravity', 'Electricity'],
    answer: 'Gravity',
  },
  {
    id: 'science-7',
    question: 'What is the largest land animal?',
    options: ['Blue Whale', 'Tiger', 'African Elephant', 'Giraffe'],
    answer: 'African Elephant',
  },
  {
    id: 'science-8',
    question: 'Which organ helps us breathe?',
    options: ['Heart', 'Lungs', 'Liver', 'Kidney'],
    answer: 'Lungs',
  },
  {
    id: 'science-9',
    question: 'Is the Sun a planet or a star?',
    options: ['A Planet', 'A Star', 'A Comet', 'A Satellite'],
    answer: 'A Star',
    acceptedAnswers: ['Star'],
  },
  {
    id: 'science-10',
    question: 'What is the hard outer layer of a tooth called?',
    options: ['Pulp', 'Dentin', 'Enamel', 'Gum'],
    answer: 'Enamel',
  },
  {
    id: 'science-11',
    question: 'Which gas do plants release during the day?',
    options: ['Carbon Dioxide', 'Nitrogen', 'Oxygen', 'Hydrogen'],
    answer: 'Oxygen',
  },
  {
    id: 'science-12',
    question: 'How many days does it take for Earth to orbit the Sun?',
    options: ['300 days', '365 days', '400 days', '730 days'],
    answer: '365 days',
  },
  {
    id: 'science-13',
    question: 'Which animal is the fastest on land?',
    options: ['Lion', 'Horse', 'Cheetah', 'Leopard'],
    answer: 'Cheetah',
  },
  {
    id: 'science-14',
    question: 'What is the boiling point of water?',
    options: ['80C', '90C', '100C', '120C'],
    answer: '100C',
    acceptedAnswers: ['100°C', '100 C', '100 degree celsius', '100 degrees celsius'],
  },
  {
    id: 'science-15',
    question: 'Which sense organ helps us taste food?',
    options: ['Nose', 'Tongue', 'Eyes', 'Ears'],
    answer: 'Tongue',
  },
  {
    id: 'science-16',
    question: 'What do we call the water that falls from clouds?',
    options: ['Snow', 'Mist', 'Rain', 'Steam'],
    answer: 'Rain',
  },
  {
    id: 'science-17',
    question: 'Which is the smallest bird in the world?',
    options: ['Sparrow', 'Parrot', 'Hummingbird', 'Crow'],
    answer: 'Hummingbird',
  },
  {
    id: 'science-18',
    question: 'What is the center of an atom called?',
    options: ['Electron', 'Nucleus', 'Proton', 'Orbit'],
    answer: 'Nucleus',
  },
  {
    id: 'science-19',
    question: 'How many kidneys does a human usually have?',
    options: ['1', '2', '3', '4'],
    answer: '2',
  },
  {
    id: 'science-20',
    question: 'Which metal is liquid at room temperature?',
    options: ['Iron', 'Copper', 'Mercury', 'Silver'],
    answer: 'Mercury',
  },
  {
    id: 'science-21',
    question: 'What is the process of plants making food called?',
    options: ['Respiration', 'Digestion', 'Photosynthesis', 'Evaporation'],
    answer: 'Photosynthesis',
  },
  {
    id: 'science-22',
    question: 'Which is the tallest animal on Earth?',
    options: ['Elephant', 'Horse', 'Giraffe', 'Camel'],
    answer: 'Giraffe',
  },
  {
    id: 'science-23',
    question: 'What protects the brain?',
    options: ['Skin', 'Rib Cage', 'Skull', 'Muscles'],
    answer: 'Skull',
  },
  {
    id: 'science-24',
    question: 'How many states of matter are there (Basic)?',
    options: ['2', '3: Solid, Liquid, Gas', '4', '5'],
    answer: '3: Solid, Liquid, Gas',
    acceptedAnswers: ['3', 'solid liquid gas'],
  },
  {
    id: 'science-25',
    question: 'What do you call a baby frog?',
    options: ['Cub', 'Pup', 'Tadpole', 'Larva'],
    answer: 'Tadpole',
  },
  {
    id: 'science-26',
    question: 'Which planet is famous for its rings?',
    options: ['Mars', 'Saturn', 'Earth', 'Venus'],
    answer: 'Saturn',
  },
  {
    id: 'science-27',
    question: 'What is the main source of energy for Earth?',
    options: ['Moon', 'The Sun', 'Wind', 'Coal'],
    answer: 'The Sun',
    acceptedAnswers: ['Sun'],
  },
  {
    id: 'science-28',
    question: 'Which instrument is used to see tiny germs?',
    options: ['Telescope', 'Microscope', 'Stethoscope', 'Periscope'],
    answer: 'Microscope',
  },
  {
    id: 'science-29',
    question: 'What is the white part of the eye called?',
    options: ['Iris', 'Pupil', 'Retina', 'Sclera'],
    answer: 'Sclera',
  },
  {
    id: 'science-30',
    question: "Which gas makes up most of the Earth's atmosphere?",
    options: ['Oxygen', 'Hydrogen', 'Nitrogen', 'Carbon Dioxide'],
    answer: 'Nitrogen',
  },
  {
    id: 'science-31',
    question: 'What is the largest planet in our solar system?',
    options: ['Jupiter', 'Mars', 'Earth', 'Venus'],
    answer: 'Jupiter',
  },
  {
    id: 'science-32',
    question: 'Which gas do plants take in during the day?',
    options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Helium'],
    answer: 'Carbon Dioxide',
  },
  {
    id: 'science-33',
    question: 'What do we call the person who travels to space?',
    options: ['Astronaut', 'Pilot', 'Sailor', 'Explorer'],
    answer: 'Astronaut',
  },
  {
    id: 'science-34',
    question: 'How many legs does an ant have?',
    options: ['4', '6', '8', '10'],
    answer: '6',
  },
  {
    id: 'science-35',
    question: 'What is the name of the galaxy we live in?',
    options: ['Andromeda', 'Whirlpool Galaxy', 'The Milky Way', 'Sombrero Galaxy'],
    answer: 'The Milky Way',
    acceptedAnswers: ['Milky Way'],
  },
  {
    id: 'science-36',
    question: 'Which part of the plant makes seeds?',
    options: ['Root', 'Stem', 'Leaf', 'Flower'],
    answer: 'Flower',
  },
  {
    id: 'science-37',
    question: 'What is the force that keeps us on the ground?',
    options: ['Magnetism', 'Gravity', 'Friction', 'Electricity'],
    answer: 'Gravity',
  },
  {
    id: 'science-38',
    question: 'Which animal can live both on land and in water?',
    options: ['Tiger', 'Eagle', 'Frog (an amphibian)', 'Camel'],
    answer: 'Frog (an amphibian)',
    acceptedAnswers: ['Frog', 'Amphibian', 'Amphibians like Frog'],
  },
  {
    id: 'science-39',
    question: 'What is the main source of heat and light for Earth?',
    options: ['The Moon', 'The Sun', 'Volcanoes', 'Electricity'],
    answer: 'The Sun',
    acceptedAnswers: ['Sun'],
  },
  {
    id: 'science-40',
    question: 'How many lungs do humans have?',
    options: ['One', 'Two', 'Three', 'Four'],
    answer: 'Two',
    acceptedAnswers: ['2'],
  },
  {
    id: 'science-41',
    question: 'What is the process of water turning into vapor called?',
    options: ['Condensation', 'Evaporation', 'Freezing', 'Melting'],
    answer: 'Evaporation',
  },
  {
    id: 'science-42',
    question: 'Which is the fastest bird in the world?',
    options: ['Eagle', 'Peregrine Falcon', 'Ostrich', 'Peacock'],
    answer: 'Peregrine Falcon',
  },
  {
    id: 'science-43',
    question: 'What do you call a scientist who studies rocks?',
    options: ['Geologist', 'Botanist', 'Astronomer', 'Zoologist'],
    answer: 'Geologist',
  },
  {
    id: 'science-44',
    question: 'Which planet is known as the Morning Star?',
    options: ['Venus', 'Mars', 'Mercury', 'Jupiter'],
    answer: 'Venus',
  },
  {
    id: 'science-45',
    question: 'What is the center of an atom called?',
    options: ['Electron', 'Nucleus', 'Proton', 'Neutron'],
    answer: 'Nucleus',
  },
  {
    id: 'science-46',
    question: 'How many days does the Earth take to go around the Sun?',
    options: ['300 days', '365 days', '400 days', '500 days'],
    answer: '365 days',
    acceptedAnswers: ['365'],
  },
  {
    id: 'science-47',
    question: 'Which vitamin do we get from sunlight?',
    options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'],
    answer: 'Vitamin D',
  },
  {
    id: 'science-48',
    question: 'What is the boiling point of water?',
    options: ['90C', '100C', '110C', '120C'],
    answer: '100C',
    acceptedAnswers: ['100°C', '100 C', '100 degree celsius', '100 degrees celsius'],
  },
  {
    id: 'science-49',
    question: 'Which is the largest bird in the world?',
    options: ['Eagle', 'Ostrich', 'Sparrow', 'Peacock'],
    answer: 'Ostrich',
  },
  {
    id: 'science-50',
    question: 'What do we use a thermometer for?',
    options: ['To measure temperature', 'To measure weight', 'To measure speed', 'To measure distance'],
    answer: 'To measure temperature',
    acceptedAnswers: ['Measure temperature', 'To measure Temperature'],
  },
  {
    id: 'science-51',
    question: 'Which planet is famous for its beautiful rings?',
    options: ['Earth', 'Saturn', 'Neptune', 'Mars'],
    answer: 'Saturn',
  },
  {
    id: 'science-52',
    question: 'What is the name of the natural satellite of Earth?',
    options: ['Sun', 'The Moon', 'Mars', 'Venus'],
    answer: 'The Moon',
    acceptedAnswers: ['Moon'],
  },
  {
    id: 'science-53',
    question: 'Which part of the body helps you see?',
    options: ['Ears', 'Nose', 'Eyes', 'Tongue'],
    answer: 'Eyes',
  },
  {
    id: 'science-54',
    question: 'What is the hardest natural substance on Earth?',
    options: ['Iron', 'Diamond', 'Gold', 'Granite'],
    answer: 'Diamond',
  },
  {
    id: 'science-55',
    question: 'Which gas is used in balloons to make them fly?',
    options: ['Oxygen', 'Hydrogen', 'Helium', 'Nitrogen'],
    answer: 'Helium',
  },
  {
    id: 'science-56',
    question: 'What do we call the study of plants?',
    options: ['Zoology', 'Botany', 'Geology', 'Chemistry'],
    answer: 'Botany',
  },
  {
    id: 'science-57',
    question: 'How many teeth does an adult human usually have?',
    options: ['28', '30', '32', '34'],
    answer: '32',
  },
  {
    id: 'science-58',
    question: "Which animal is known as the 'King of the Jungle'?",
    options: ['Tiger', 'Lion', 'Leopard', 'Elephant'],
    answer: 'Lion',
  },
  {
    id: 'science-59',
    question: 'What is the liquid part of a cell called?',
    options: ['Nucleus', 'Cytoplasm', 'Cell Wall', 'Membrane'],
    answer: 'Cytoplasm',
  },
  {
    id: 'science-60',
    question: 'What is the smallest unit of life?',
    options: ['Atom', 'Molecule', 'Cell', 'Tissue'],
    answer: 'Cell',
  },
  {
    id: 'science-61',
    question: 'Which planet is the coldest in our solar system?',
    options: ['Mars', 'Neptune', 'Venus', 'Mercury'],
    answer: 'Neptune',
  },
  {
    id: 'science-62',
    question: 'What is the green pigment in plants called?',
    options: ['Hemoglobin', 'Chlorophyll', 'Melanin', 'Carotene'],
    answer: 'Chlorophyll',
  },
  {
    id: 'science-63',
    question: 'Which sense organ helps us hear?',
    options: ['Eyes', 'Ears', 'Nose', 'Skin'],
    answer: 'Ears',
  },
  {
    id: 'science-64',
    question: 'What is the chemical formula for water?',
    options: ['CO2', 'H2O', 'O2', 'NaCl'],
    answer: 'H2O',
    acceptedAnswers: ['H₂O', 'h2o'],
  },
  {
    id: 'science-65',
    question: 'Which bird cannot fly but is a great swimmer?',
    options: ['Duck', 'Penguin', 'Eagle', 'Parrot'],
    answer: 'Penguin',
  },
  {
    id: 'science-66',
    question: 'What do we call the seasonal movement of animals?',
    options: ['Hibernation', 'Adaptation', 'Migration', 'Reproduction'],
    answer: 'Migration',
  },
  {
    id: 'science-67',
    question: 'Which is the largest ocean on Earth?',
    options: ['Indian Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Pacific Ocean'],
    answer: 'Pacific Ocean',
  },
  {
    id: 'science-68',
    question: 'What is the freezing point of water?',
    options: ['0C', '10C', '50C', '100C'],
    answer: '0C',
    acceptedAnswers: ['0°C', '0 C', '0 degree celsius', '0 degrees celsius'],
  },
  {
    id: 'science-69',
    question: 'Which part of the plant carries water to the leaves?',
    options: ['Root', 'Flower', 'Stem', 'Fruit'],
    answer: 'Stem',
  },
  {
    id: 'science-70',
    question: 'How many hearts does an octopus have?',
    options: ['One', 'Two', 'Three', 'Four'],
    answer: 'Three',
    acceptedAnswers: ['3'],
  },
  {
    id: 'science-71',
    question: 'What is the name of the layer that protects Earth from UV rays?',
    options: ['Troposphere', 'Ionosphere', 'Ozone Layer', 'Magnetosphere'],
    answer: 'Ozone Layer',
  },
  {
    id: 'science-72',
    question: "Which gas is most abundant in Earth's atmosphere?",
    options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Argon'],
    answer: 'Nitrogen',
  },
  {
    id: 'science-73',
    question: 'What do we call animals that eat only plants?',
    options: ['Carnivores', 'Omnivores', 'Herbivores', 'Insectivores'],
    answer: 'Herbivores',
  },
  {
    id: 'science-74',
    question: 'Which planet is closest to the Sun?',
    options: ['Venus', 'Earth', 'Mercury', 'Mars'],
    answer: 'Mercury',
  },
  {
    id: 'science-75',
    question: 'What is the main organ of the respiratory system?',
    options: ['Heart', 'Liver', 'Lungs', 'Kidney'],
    answer: 'Lungs',
  },
  {
    id: 'science-76',
    question: 'Which metal is liquid at room temperature?',
    options: ['Mercury', 'Iron', 'Aluminum', 'Copper'],
    answer: 'Mercury',
  },
  {
    id: 'science-77',
    question: 'What is the sound of a snake called?',
    options: ['Roar', 'Chirp', 'Hiss', 'Buzz'],
    answer: 'Hiss',
  },
  {
    id: 'science-78',
    question: 'Which planet is known as the Blue Planet?',
    options: ['Earth', 'Neptune', 'Venus', 'Saturn'],
    answer: 'Earth',
  },
  {
    id: 'science-79',
    question: 'How many states of matter are there (Basic)?',
    options: ['Two', 'Three: Solid, Liquid, Gas', 'Four', 'Five'],
    answer: 'Three: Solid, Liquid, Gas',
    acceptedAnswers: ['3', 'solid liquid gas'],
  },
  {
    id: 'science-80',
    question: 'What is the speed of light approximately?',
    options: ['30,000 km/s', '300,000 km/s', '3,000 km/s', '3,000,000 km/s'],
    answer: '300,000 km/s',
    acceptedAnswers: ['300000 km/s', '3x10^5 km/s'],
  },
  {
    id: 'science-81',
    question: 'What do we call the doctor who treats animals?',
    options: ['Pediatrician', 'Veterinarian', 'Dermatologist', 'Cardiologist'],
    answer: 'Veterinarian',
    acceptedAnswers: ['Vet'],
  },
  {
    id: 'science-82',
    question: 'Which is the smallest planet in our solar system?',
    options: ['Mercury', 'Mars', 'Venus', 'Earth'],
    answer: 'Mercury',
  },
  {
    id: 'science-83',
    question: 'What is the process of a seed growing into a plant called?',
    options: ['Pollination', 'Photosynthesis', 'Germination', 'Respiration'],
    answer: 'Germination',
  },
  {
    id: 'science-84',
    question: 'Which organ in our body helps us digest food?',
    options: ['Heart', 'Lungs', 'Stomach', 'Brain'],
    answer: 'Stomach',
  },
  {
    id: 'science-85',
    question: 'What is the outer layer of Earth called?',
    options: ['Mantle', 'Core', 'Crust', 'Atmosphere'],
    answer: 'Crust',
  },
  {
    id: 'science-86',
    question: 'Which animal sleeps standing up?',
    options: ['Horse', 'Cat', 'Rabbit', 'Bear'],
    answer: 'Horse',
  },
  {
    id: 'science-87',
    question: 'What do we call a group of stars that form a pattern?',
    options: ['Galaxy', 'Constellation', 'Cluster', 'Orbit'],
    answer: 'Constellation',
  },
  {
    id: 'science-88',
    question: 'Which gas do humans breathe out?',
    options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Helium'],
    answer: 'Carbon Dioxide',
  },
  {
    id: 'science-89',
    question: 'What is the study of weather called?',
    options: ['Biology', 'Meteorology', 'Astronomy', 'Geography'],
    answer: 'Meteorology',
  },
  {
    id: 'science-90',
    question: 'Which part of the tree tells its age?',
    options: ['Leaves', 'Roots', 'Rings in the trunk', 'Bark color'],
    answer: 'Rings in the trunk',
    acceptedAnswers: ['Tree rings', 'Rings'],
  },
  {
    id: 'science-91',
    question: 'What is the strongest muscle in the human body?',
    options: ['Biceps', 'Quadriceps', 'Masseter (jaw muscle)', 'Heart'],
    answer: 'Masseter (jaw muscle)',
    acceptedAnswers: ['Masseter', 'Jaw muscle', 'Masseter jaw muscle'],
  },
  {
    id: 'science-92',
    question: 'Which planet has the most moons?',
    options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    answer: 'Saturn',
  },
  {
    id: 'science-93',
    question: 'What is the name of the red planet?',
    options: ['Mercury', 'Venus', 'Mars', 'Jupiter'],
    answer: 'Mars',
  },
  {
    id: 'science-94',
    question: 'Which animal has the longest neck?',
    options: ['Elephant', 'Horse', 'Giraffe', 'Camel'],
    answer: 'Giraffe',
  },
  {
    id: 'science-95',
    question: 'What is the primary source of energy for the water cycle?',
    options: ['Wind', 'The Sun', 'Moonlight', 'Tides'],
    answer: 'The Sun',
    acceptedAnswers: ['Sun'],
  },
  {
    id: 'science-96',
    question: 'Which part of the ear helps with balance?',
    options: ['Outer Ear', 'Middle Ear', 'Inner Ear', 'Eardrum'],
    answer: 'Inner Ear',
  },
  {
    id: 'science-97',
    question: 'What do we call the remains of ancient animals found in rocks?',
    options: ['Minerals', 'Fossils', 'Crystals', 'Sediments'],
    answer: 'Fossils',
  },
  {
    id: 'science-98',
    question: 'Which planet rotates on its side?',
    options: ['Earth', 'Uranus', 'Mars', 'Mercury'],
    answer: 'Uranus',
  },
  {
    id: 'science-99',
    question: 'What is the name of the first human to step on the Moon?',
    options: ['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'Kalpana Chawla'],
    answer: 'Neil Armstrong',
  },
  {
    id: 'science-100',
    question: 'Which gas is essential for fire to burn?',
    options: ['Nitrogen', 'Carbon Dioxide', 'Oxygen', 'Hydrogen'],
    answer: 'Oxygen',
  },
];

export const JUNIOR_NUMBERS_QUIZ_QUESTIONS = [
  {
    id: 'numbers-1',
    question: 'What number comes after 9?',
    options: ['8', '10', '11', '12'],
    answer: '10',
  },
  {
    id: 'numbers-2',
    question: 'What number comes before 50?',
    options: ['48', '49', '51', '52'],
    answer: '49',
  },
  {
    id: 'numbers-3',
    question: 'What is the smallest two-digit number?',
    options: ['1', '9', '10', '11'],
    answer: '10',
  },
  {
    id: 'numbers-4',
    question: 'What is the largest one-digit number?',
    options: ['8', '9', '10', '11'],
    answer: '9',
  },
  {
    id: 'numbers-5',
    question: 'Which of these is an even number?',
    options: ['23', '37', '48', '55'],
    answer: '48',
  },
  {
    id: 'numbers-6',
    question: 'Which of these is an odd number?',
    options: ['12', '24', '36', '45'],
    answer: '45',
  },
  {
    id: 'numbers-7',
    question: 'What is 7 + 5?',
    options: ['10', '11', '12', '13'],
    answer: '12',
  },
  {
    id: 'numbers-8',
    question: 'What is 15 - 6?',
    options: ['7', '8', '9', '10'],
    answer: '9',
  },
  {
    id: 'numbers-9',
    question: 'What is 9 x 2?',
    options: ['16', '18', '20', '22'],
    answer: '18',
  },
  {
    id: 'numbers-10',
    question: 'What is 20 / 4?',
    options: ['4', '5', '6', '8'],
    answer: '5',
  },
  {
    id: 'numbers-11',
    question: 'What is the place value of 5 in 58?',
    options: ['5', '50', '500', '8'],
    answer: '50',
  },
  {
    id: 'numbers-12',
    question: 'What number is made by 3 hundreds, 4 tens and 2 ones?',
    options: ['324', '342', '432', '243'],
    answer: '342',
  },
  {
    id: 'numbers-13',
    question: 'What is the Roman numeral for 10?',
    options: ['V', 'X', 'L', 'C'],
    answer: 'X',
  },
  {
    id: 'numbers-14',
    question: 'How many sides does a triangle have?',
    options: ['2', '3', '4', '5'],
    answer: '3',
  },
  {
    id: 'numbers-15',
    question: 'What is half of 100?',
    options: ['25', '40', '50', '60'],
    answer: '50',
  },
  {
    id: 'numbers-16',
    question: 'What is double of 14?',
    options: ['26', '27', '28', '29'],
    answer: '28',
  },
  {
    id: 'numbers-17',
    question: 'Which number is greater?',
    options: ['67', '76', '56', '66'],
    answer: '76',
  },
  {
    id: 'numbers-18',
    question: 'Which number is smaller?',
    options: ['91', '19', '29', '39'],
    answer: '19',
  },
  {
    id: 'numbers-19',
    question: 'Find the next number: 2, 4, 6, 8, ?',
    options: ['9', '10', '11', '12'],
    answer: '10',
  },
  {
    id: 'numbers-20',
    question: 'Find the next number: 5, 10, 15, 20, ?',
    options: ['22', '24', '25', '30'],
    answer: '25',
  },
  {
    id: 'numbers-21',
    question: 'What is 100 - 45?',
    options: ['45', '50', '55', '65'],
    answer: '55',
  },
  {
    id: 'numbers-22',
    question: 'What is 11 + 11?',
    options: ['20', '21', '22', '23'],
    answer: '22',
  },
  {
    id: 'numbers-23',
    question: 'What is one-quarter of 20?',
    options: ['4', '5', '6', '8'],
    answer: '5',
  },
  {
    id: 'numbers-24',
    question: 'How many months are there in one year?',
    options: ['10', '11', '12', '13'],
    answer: '12',
  },
  {
    id: 'numbers-25',
    question: 'How many minutes are there in one hour?',
    options: ['30', '45', '60', '90'],
    answer: '60',
  },
  {
    id: 'numbers-26',
    question: 'Which of these is a prime number?',
    options: ['9', '15', '21', '29'],
    answer: '29',
  },
  {
    id: 'numbers-27',
    question: 'What is 30 + 70?',
    options: ['90', '100', '110', '120'],
    answer: '100',
  },
  {
    id: 'numbers-28',
    question: 'What is 90 / 10?',
    options: ['7', '8', '9', '10'],
    answer: '9',
  },
  {
    id: 'numbers-29',
    question: 'If you have 3 tens and 6 ones, what is the number?',
    options: ['30', '33', '36', '63'],
    answer: '36',
  },
  {
    id: 'numbers-30',
    question: 'Which number is closest to 100?',
    options: ['89', '95', '99', '120'],
    answer: '99',
  },
  {
    id: 'numbers-31',
    question: 'What comes after 99?',
    options: ['98', '99', '100', '101'],
    answer: '100',
  },
  {
    id: 'numbers-32',
    question: "Spell the number '50'.",
    options: ['Fifty', 'Forty', 'Sixty', 'Fifteen'],
    answer: 'Fifty',
    acceptedAnswers: ['50'],
  },
  {
    id: 'numbers-33',
    question: 'Which is bigger: 45 or 54?',
    options: ['45', '54', 'Both are equal', 'Cannot say'],
    answer: '54',
  },
  {
    id: 'numbers-34',
    question: 'What is 10 + 5?',
    options: ['14', '15', '16', '20'],
    answer: '15',
  },
  {
    id: 'numbers-35',
    question: 'What is half of 20?',
    options: ['5', '10', '15', '20'],
    answer: '10',
  },
  {
    id: 'numbers-36',
    question: 'What is 20 - 5?',
    options: ['10', '15', '20', '25'],
    answer: '15',
  },
  {
    id: 'numbers-37',
    question: 'Count the sides of a triangle.',
    options: ['2', '3', '4', '5'],
    answer: '3',
  },
  {
    id: 'numbers-38',
    question: 'What is 5 more than 15?',
    options: ['18', '19', '20', '25'],
    answer: '20',
  },
  {
    id: 'numbers-39',
    question: 'Missing number: 10, 20, _, 40.',
    options: ['15', '25', '30', '35'],
    answer: '30',
  },
  {
    id: 'numbers-40',
    question: 'How many tens are in 40?',
    options: ['2', '3', '4', '5'],
    answer: '4',
  },
  {
    id: 'numbers-41',
    question: 'What comes before 200?',
    options: ['198', '199', '200', '201'],
    answer: '199',
  },
  {
    id: 'numbers-42',
    question: "Spell the number '90'.",
    options: ['Ninety', 'Nineteen', 'Nine', 'Ninteen'],
    answer: 'Ninety',
    acceptedAnswers: ['90'],
  },
  {
    id: 'numbers-43',
    question: 'Which is smaller: 72 or 27?',
    options: ['72', '27', 'Both are equal', 'Cannot say'],
    answer: '27',
  },
  {
    id: 'numbers-44',
    question: 'What is 8 + 7?',
    options: ['14', '15', '16', '17'],
    answer: '15',
  },
  {
    id: 'numbers-45',
    question: 'What is 25 - 10?',
    options: ['10', '15', '20', '25'],
    answer: '15',
  },
  {
    id: 'numbers-46',
    question: 'What is double of 9?',
    options: ['16', '17', '18', '19'],
    answer: '18',
  },
  {
    id: 'numbers-47',
    question: 'What is half of 50?',
    options: ['20', '25', '30', '35'],
    answer: '25',
  },
  {
    id: 'numbers-48',
    question: 'Missing number: 2, 4, 6, _, 10.',
    options: ['7', '8', '9', '11'],
    answer: '8',
  },
  {
    id: 'numbers-49',
    question: 'How many ones are in 34?',
    options: ['3', '4', '30', '34'],
    answer: '4',
  },
  {
    id: 'numbers-50',
    question: 'How many tens are in 90?',
    options: ['7', '8', '9', '10'],
    answer: '9',
  },
  {
    id: 'numbers-51',
    question: 'What comes after 149?',
    options: ['148', '149', '150', '151'],
    answer: '150',
  },
  {
    id: 'numbers-52',
    question: 'What is 30 + 20?',
    options: ['40', '45', '50', '60'],
    answer: '50',
  },
  {
    id: 'numbers-53',
    question: 'What is 100 - 25?',
    options: ['65', '70', '75', '80'],
    answer: '75',
  },
  {
    id: 'numbers-54',
    question: 'Which of these is an even number?',
    options: ['73', '84', '95', '61'],
    answer: '84',
  },
  {
    id: 'numbers-55',
    question: 'Which of these is an odd number?',
    options: ['22', '40', '57', '68'],
    answer: '57',
  },
  {
    id: 'numbers-56',
    question: 'Missing number: 5, 10, 15, _, 25.',
    options: ['18', '19', '20', '30'],
    answer: '20',
  },
  {
    id: 'numbers-57',
    question: 'What is 3 more than 17?',
    options: ['18', '19', '20', '21'],
    answer: '20',
  },
  {
    id: 'numbers-58',
    question: 'What is 10 less than 45?',
    options: ['30', '35', '40', '55'],
    answer: '35',
  },
  {
    id: 'numbers-59',
    question: 'What number has 6 tens and 2 ones?',
    options: ['26', '62', '206', '602'],
    answer: '62',
  },
  {
    id: 'numbers-60',
    question: 'What is the place value of 7 in 78?',
    options: ['7', '8', '70', '700'],
    answer: '70',
  },
  {
    id: 'numbers-61',
    question: 'Which is bigger: 89 or 98?',
    options: ['89', '98', 'Both are equal', 'Cannot say'],
    answer: '98',
  },
  {
    id: 'numbers-62',
    question: "Spell the number '100'.",
    options: ['One Hundred', 'Hundred One', 'One Thousand', 'Ten Hundred'],
    answer: 'One Hundred',
    acceptedAnswers: ['100'],
  },
  {
    id: 'numbers-63',
    question: 'What is 40 / 5?',
    options: ['6', '7', '8', '9'],
    answer: '8',
  },
  {
    id: 'numbers-64',
    question: 'What is 9 + 9?',
    options: ['16', '17', '18', '19'],
    answer: '18',
  },
  {
    id: 'numbers-65',
    question: 'What is 60 - 30?',
    options: ['20', '25', '30', '35'],
    answer: '30',
  },
  {
    id: 'numbers-66',
    question: 'How many sides does a square have?',
    options: ['3', '4', '5', '6'],
    answer: '4',
  },
  {
    id: 'numbers-67',
    question: 'What is 7 more than 21?',
    options: ['26', '27', '28', '29'],
    answer: '28',
  },
  {
    id: 'numbers-68',
    question: 'Missing number: 30, 40, 50, _, 70.',
    options: ['55', '60', '65', '75'],
    answer: '60',
  },
  {
    id: 'numbers-69',
    question: 'What number comes before 1?',
    options: ['-1', '0', '1', '2'],
    answer: '0',
  },
  {
    id: 'numbers-70',
    question: 'What is half of 18?',
    options: ['8', '9', '10', '12'],
    answer: '9',
  },
  {
    id: 'numbers-71',
    question: 'What is double of 25?',
    options: ['45', '50', '55', '60'],
    answer: '50',
  },
  {
    id: 'numbers-72',
    question: 'What is 15 + 15?',
    options: ['25', '30', '35', '40'],
    answer: '30',
  },
  {
    id: 'numbers-73',
    question: 'What is 45 - 15?',
    options: ['20', '25', '30', '35'],
    answer: '30',
  },
  {
    id: 'numbers-74',
    question: 'Which is greater: 120 or 102?',
    options: ['120', '102', 'Both are equal', 'Cannot say'],
    answer: '120',
  },
  {
    id: 'numbers-75',
    question: 'How many tens are in 70?',
    options: ['5', '6', '7', '8'],
    answer: '7',
  },
  {
    id: 'numbers-76',
    question: 'What is the place value of 3 in 35?',
    options: ['3', '5', '30', '300'],
    answer: '30',
  },
  {
    id: 'numbers-77',
    question: 'Missing number: 100, 90, 80, _, 60.',
    options: ['65', '70', '75', '85'],
    answer: '70',
  },
  {
    id: 'numbers-78',
    question: 'What is 2 less than 30?',
    options: ['26', '27', '28', '29'],
    answer: '28',
  },
  {
    id: 'numbers-79',
    question: 'What is 11 + 12?',
    options: ['21', '22', '23', '24'],
    answer: '23',
  },
  {
    id: 'numbers-80',
    question: 'What is 50 - 27?',
    options: ['21', '22', '23', '24'],
    answer: '23',
  },
  {
    id: 'numbers-81',
    question: 'What comes after 399?',
    options: ['398', '399', '400', '401'],
    answer: '400',
  },
  {
    id: 'numbers-82',
    question: "Spell the number '75'.",
    options: ['Seventy Five', 'Seventeen Five', 'Sixty Five', 'Seventy'],
    answer: 'Seventy Five',
    acceptedAnswers: ['75', 'Seventy-Five'],
  },
  {
    id: 'numbers-83',
    question: 'Which is the smallest number?',
    options: ['101', '110', '11', '111'],
    answer: '11',
  },
  {
    id: 'numbers-84',
    question: 'What is 6 x 5?',
    options: ['25', '30', '35', '40'],
    answer: '30',
  },
  {
    id: 'numbers-85',
    question: 'What is 84 / 7?',
    options: ['10', '11', '12', '13'],
    answer: '12',
  },
  {
    id: 'numbers-86',
    question: 'What is 5 more than 95?',
    options: ['99', '100', '101', '105'],
    answer: '100',
  },
  {
    id: 'numbers-87',
    question: 'What is 100 - 99?',
    options: ['0', '1', '2', '10'],
    answer: '1',
  },
  {
    id: 'numbers-88',
    question: 'Missing number: 1, 3, 5, _, 9.',
    options: ['6', '7', '8', '10'],
    answer: '7',
  },
  {
    id: 'numbers-89',
    question: 'How many sides does a pentagon have?',
    options: ['4', '5', '6', '7'],
    answer: '5',
  },
  {
    id: 'numbers-90',
    question: 'What is one-quarter of 20?',
    options: ['4', '5', '6', '10'],
    answer: '5',
  },
  {
    id: 'numbers-91',
    question: 'What number has 9 tens and 8 ones?',
    options: ['89', '98', '908', '980'],
    answer: '98',
  },
  {
    id: 'numbers-92',
    question: 'What is the place value of 4 in 146?',
    options: ['4', '40', '400', '6'],
    answer: '40',
  },
  {
    id: 'numbers-93',
    question: 'Which is bigger: 1000 or 999?',
    options: ['999', '1000', 'Both are equal', 'Cannot say'],
    answer: '1000',
  },
  {
    id: 'numbers-94',
    question: 'What is 200 - 150?',
    options: ['40', '50', '60', '70'],
    answer: '50',
  },
  {
    id: 'numbers-95',
    question: 'What is 14 + 16?',
    options: ['28', '29', '30', '31'],
    answer: '30',
  },
  {
    id: 'numbers-96',
    question: 'What is 3 dozens?',
    options: ['24', '30', '36', '40'],
    answer: '36',
    acceptedAnswers: ['Three dozens', 'Three dozen'],
  },
  {
    id: 'numbers-97',
    question: 'Missing number: 12, 24, 36, _, 60.',
    options: ['42', '48', '54', '58'],
    answer: '48',
  },
  {
    id: 'numbers-98',
    question: 'What is 18 less than 50?',
    options: ['30', '31', '32', '33'],
    answer: '32',
  },
  {
    id: 'numbers-99',
    question: 'What is the smallest 3-digit number?',
    options: ['10', '99', '100', '101'],
    answer: '100',
  },
  {
    id: 'numbers-100',
    question: 'What is 999 + 1?',
    options: ['999', '1000', '1001', '1100'],
    answer: '1000',
  },
];

export const JUNIOR_TABLES_QUIZ_QUESTIONS = [
  {
    id: 'tables-1',
    question: 'What is 2 x 3?',
    options: ['5', '6', '7', '8'],
    answer: '6',
  },
  {
    id: 'tables-2',
    question: 'What is 4 x 5?',
    options: ['18', '20', '22', '24'],
    answer: '20',
  },
  {
    id: 'tables-3',
    question: 'What is 6 x 7?',
    options: ['36', '40', '42', '48'],
    answer: '42',
  },
  {
    id: 'tables-4',
    question: 'What is 8 x 9?',
    options: ['64', '72', '81', '96'],
    answer: '72',
  },
  {
    id: 'tables-5',
    question: 'What is 9 x 9?',
    options: ['72', '81', '90', '99'],
    answer: '81',
  },
  {
    id: 'tables-6',
    question: 'What is 12 x 2?',
    options: ['22', '24', '26', '28'],
    answer: '24',
  },
  {
    id: 'tables-7',
    question: 'What is 11 x 3?',
    options: ['30', '33', '36', '39'],
    answer: '33',
  },
  {
    id: 'tables-8',
    question: 'What is 7 x 8?',
    options: ['49', '54', '56', '63'],
    answer: '56',
  },
  {
    id: 'tables-9',
    question: 'What is 5 x 6?',
    options: ['25', '30', '35', '40'],
    answer: '30',
  },
  {
    id: 'tables-10',
    question: 'What is 10 x 10?',
    options: ['90', '95', '100', '110'],
    answer: '100',
  },
  {
    id: 'tables-11',
    question: 'What is 3 x 12?',
    options: ['30', '33', '36', '39'],
    answer: '36',
  },
  {
    id: 'tables-12',
    question: 'What is 4 x 9?',
    options: ['28', '32', '36', '40'],
    answer: '36',
  },
  {
    id: 'tables-13',
    question: 'What is 6 x 6?',
    options: ['30', '32', '34', '36'],
    answer: '36',
  },
  {
    id: 'tables-14',
    question: 'What is 8 x 7?',
    options: ['48', '54', '56', '64'],
    answer: '56',
  },
  {
    id: 'tables-15',
    question: 'What is 12 x 12?',
    options: ['124', '132', '144', '156'],
    answer: '144',
  },
  {
    id: 'tables-16',
    question: 'What is 15 x 2?',
    options: ['28', '30', '32', '35'],
    answer: '30',
  },
  {
    id: 'tables-17',
    question: 'What is 14 x 3?',
    options: ['36', '40', '42', '44'],
    answer: '42',
  },
  {
    id: 'tables-18',
    question: 'What is 9 x 4?',
    options: ['27', '32', '36', '45'],
    answer: '36',
  },
  {
    id: 'tables-19',
    question: 'What is 13 x 5?',
    options: ['55', '60', '65', '70'],
    answer: '65',
  },
  {
    id: 'tables-20',
    question: 'What is 7 x 11?',
    options: ['70', '72', '77', '84'],
    answer: '77',
  },
  {
    id: 'tables-21',
    question: 'What is 16 x 2?',
    options: ['30', '32', '34', '36'],
    answer: '32',
  },
  {
    id: 'tables-22',
    question: 'What is 18 x 3?',
    options: ['48', '52', '54', '56'],
    answer: '54',
  },
  {
    id: 'tables-23',
    question: 'What is 25 x 4?',
    options: ['90', '95', '100', '105'],
    answer: '100',
  },
  {
    id: 'tables-24',
    question: 'What is 9 x 12?',
    options: ['96', '99', '108', '120'],
    answer: '108',
  },
  {
    id: 'tables-25',
    question: 'What is 6 x 11?',
    options: ['60', '64', '66', '72'],
    answer: '66',
  },
  {
    id: 'tables-26',
    question: 'What is 8 x 12?',
    options: ['88', '92', '96', '104'],
    answer: '96',
  },
  {
    id: 'tables-27',
    question: 'What is 17 x 5?',
    options: ['75', '80', '85', '90'],
    answer: '85',
  },
  {
    id: 'tables-28',
    question: 'What is 19 x 2?',
    options: ['36', '38', '40', '42'],
    answer: '38',
  },
  {
    id: 'tables-29',
    question: 'What is 20 x 7?',
    options: ['120', '130', '140', '150'],
    answer: '140',
  },
  {
    id: 'tables-30',
    question: 'What is 15 x 6?',
    options: ['75', '80', '85', '90'],
    answer: '90',
  },
  {
    id: 'tables-31',
    question: 'What is 4 x 9?',
    options: ['32', '34', '36', '38'],
    answer: '36',
  },
  {
    id: 'tables-32',
    question: 'What is 5 x 7?',
    options: ['30', '35', '40', '45'],
    answer: '35',
  },
  {
    id: 'tables-33',
    question: 'What is 6 x 8?',
    options: ['42', '46', '48', '52'],
    answer: '48',
  },
  {
    id: 'tables-34',
    question: 'What is 7 x 7?',
    options: ['42', '45', '49', '56'],
    answer: '49',
  },
  {
    id: 'tables-35',
    question: 'What is 8 x 6?',
    options: ['42', '46', '48', '54'],
    answer: '48',
  },
  {
    id: 'tables-36',
    question: 'What is 9 x 4?',
    options: ['27', '32', '36', '40'],
    answer: '36',
  },
  {
    id: 'tables-37',
    question: 'What is 3 x 12?',
    options: ['30', '33', '36', '39'],
    answer: '36',
  },
  {
    id: 'tables-38',
    question: 'What is 10 x 10?',
    options: ['90', '95', '100', '110'],
    answer: '100',
  },
  {
    id: 'tables-39',
    question: 'What is 2 x 15?',
    options: ['25', '30', '35', '40'],
    answer: '30',
  },
  {
    id: 'tables-40',
    question: 'What is 11 x 3?',
    options: ['30', '33', '36', '39'],
    answer: '33',
  },
  {
    id: 'tables-41',
    question: 'What is 12 x 5?',
    options: ['50', '55', '60', '65'],
    answer: '60',
  },
  {
    id: 'tables-42',
    question: 'What is 13 x 3?',
    options: ['36', '39', '42', '45'],
    answer: '39',
  },
  {
    id: 'tables-43',
    question: 'What is 14 x 2?',
    options: ['24', '26', '28', '30'],
    answer: '28',
  },
  {
    id: 'tables-44',
    question: 'What is 15 x 4?',
    options: ['45', '50', '60', '75'],
    answer: '60',
  },
  {
    id: 'tables-45',
    question: 'What is 16 x 3?',
    options: ['42', '45', '48', '52'],
    answer: '48',
  },
  {
    id: 'tables-46',
    question: 'What is 17 x 2?',
    options: ['32', '34', '36', '38'],
    answer: '34',
  },
  {
    id: 'tables-47',
    question: 'What is 18 x 2?',
    options: ['34', '36', '38', '40'],
    answer: '36',
  },
  {
    id: 'tables-48',
    question: 'What is 19 x 2?',
    options: ['36', '38', '40', '42'],
    answer: '38',
  },
  {
    id: 'tables-49',
    question: 'What is 20 x 2?',
    options: ['20', '30', '40', '50'],
    answer: '40',
  },
  {
    id: 'tables-50',
    question: 'What is 12 x 6?',
    options: ['66', '70', '72', '76'],
    answer: '72',
  },
  {
    id: 'tables-51',
    question: 'What is 13 x 4?',
    options: ['48', '50', '52', '54'],
    answer: '52',
  },
  {
    id: 'tables-52',
    question: 'What is 14 x 3?',
    options: ['39', '40', '42', '45'],
    answer: '42',
  },
  {
    id: 'tables-53',
    question: 'What is 15 x 5?',
    options: ['70', '75', '80', '85'],
    answer: '75',
  },
  {
    id: 'tables-54',
    question: 'What is 16 x 4?',
    options: ['60', '62', '64', '68'],
    answer: '64',
  },
  {
    id: 'tables-55',
    question: 'What is 17 x 3?',
    options: ['48', '51', '54', '57'],
    answer: '51',
  },
  {
    id: 'tables-56',
    question: 'What is 18 x 4?',
    options: ['68', '70', '72', '74'],
    answer: '72',
  },
  {
    id: 'tables-57',
    question: 'What is 19 x 3?',
    options: ['54', '57', '60', '63'],
    answer: '57',
  },
  {
    id: 'tables-58',
    question: 'What is 20 x 3?',
    options: ['40', '50', '60', '70'],
    answer: '60',
  },
  {
    id: 'tables-59',
    question: 'What is 11 x 6?',
    options: ['55', '60', '66', '72'],
    answer: '66',
  },
  {
    id: 'tables-60',
    question: 'What is 9 x 8?',
    options: ['64', '70', '72', '81'],
    answer: '72',
  },
  {
    id: 'tables-61',
    question: 'What is 7 x 9?',
    options: ['56', '63', '72', '81'],
    answer: '63',
  },
  {
    id: 'tables-62',
    question: 'What is 6 x 12?',
    options: ['60', '66', '72', '78'],
    answer: '72',
  },
  {
    id: 'tables-63',
    question: 'What is 5 x 12?',
    options: ['50', '55', '60', '65'],
    answer: '60',
  },
  {
    id: 'tables-64',
    question: 'What is 4 x 12?',
    options: ['40', '44', '48', '52'],
    answer: '48',
  },
  {
    id: 'tables-65',
    question: 'What is 3 x 15?',
    options: ['42', '45', '48', '50'],
    answer: '45',
  },
  {
    id: 'tables-66',
    question: 'What is 2 x 18?',
    options: ['32', '34', '36', '38'],
    answer: '36',
  },
  {
    id: 'tables-67',
    question: 'What is 10 x 12?',
    options: ['100', '110', '120', '130'],
    answer: '120',
  },
  {
    id: 'tables-68',
    question: 'What is 8 x 11?',
    options: ['80', '84', '88', '92'],
    answer: '88',
  },
  {
    id: 'tables-69',
    question: 'What is 7 x 12?',
    options: ['77', '84', '91', '98'],
    answer: '84',
  },
  {
    id: 'tables-70',
    question: 'What is 6 x 13?',
    options: ['72', '76', '78', '82'],
    answer: '78',
  },
  {
    id: 'tables-71',
    question: 'What is 5 x 14?',
    options: ['60', '65', '70', '75'],
    answer: '70',
  },
  {
    id: 'tables-72',
    question: 'What is 4 x 15?',
    options: ['52', '56', '60', '64'],
    answer: '60',
  },
  {
    id: 'tables-73',
    question: 'What is 3 x 16?',
    options: ['45', '48', '51', '54'],
    answer: '48',
  },
  {
    id: 'tables-74',
    question: 'What is 2 x 19?',
    options: ['34', '36', '38', '40'],
    answer: '38',
  },
  {
    id: 'tables-75',
    question: 'What is 12 x 7?',
    options: ['72', '78', '84', '90'],
    answer: '84',
  },
  {
    id: 'tables-76',
    question: 'What is 13 x 5?',
    options: ['55', '60', '65', '70'],
    answer: '65',
  },
  {
    id: 'tables-77',
    question: 'What is 14 x 4?',
    options: ['52', '56', '60', '64'],
    answer: '56',
  },
  {
    id: 'tables-78',
    question: 'What is 15 x 6?',
    options: ['80', '85', '90', '95'],
    answer: '90',
  },
  {
    id: 'tables-79',
    question: 'What is 16 x 5?',
    options: ['70', '75', '80', '85'],
    answer: '80',
  },
  {
    id: 'tables-80',
    question: 'What is 17 x 4?',
    options: ['64', '66', '68', '72'],
    answer: '68',
  },
  {
    id: 'tables-81',
    question: 'What is 18 x 5?',
    options: ['80', '85', '90', '95'],
    answer: '90',
  },
  {
    id: 'tables-82',
    question: 'What is 19 x 4?',
    options: ['72', '74', '76', '78'],
    answer: '76',
  },
  {
    id: 'tables-83',
    question: 'What is 20 x 4?',
    options: ['60', '70', '80', '90'],
    answer: '80',
  },
  {
    id: 'tables-84',
    question: 'What is 11 x 7?',
    options: ['66', '72', '77', '84'],
    answer: '77',
  },
  {
    id: 'tables-85',
    question: 'What is 12 x 8?',
    options: ['84', '90', '96', '102'],
    answer: '96',
  },
  {
    id: 'tables-86',
    question: 'What is 13 x 6?',
    options: ['72', '75', '78', '81'],
    answer: '78',
  },
  {
    id: 'tables-87',
    question: 'What is 14 x 5?',
    options: ['65', '70', '75', '80'],
    answer: '70',
  },
  {
    id: 'tables-88',
    question: 'What is 15 x 7?',
    options: ['98', '100', '105', '110'],
    answer: '105',
  },
  {
    id: 'tables-89',
    question: 'What is 16 x 6?',
    options: ['88', '92', '96', '102'],
    answer: '96',
  },
  {
    id: 'tables-90',
    question: 'What is 17 x 5?',
    options: ['75', '80', '85', '90'],
    answer: '85',
  },
  {
    id: 'tables-91',
    question: 'What is 18 x 6?',
    options: ['96', '102', '108', '114'],
    answer: '108',
  },
  {
    id: 'tables-92',
    question: 'What is 19 x 5?',
    options: ['85', '90', '95', '100'],
    answer: '95',
  },
  {
    id: 'tables-93',
    question: 'What is 20 x 5?',
    options: ['80', '90', '100', '110'],
    answer: '100',
  },
  {
    id: 'tables-94',
    question: 'What is 11 x 8?',
    options: ['77', '88', '99', '108'],
    answer: '88',
  },
  {
    id: 'tables-95',
    question: 'What is 12 x 9?',
    options: ['96', '102', '108', '114'],
    answer: '108',
  },
  {
    id: 'tables-96',
    question: 'What is 13 x 7?',
    options: ['84', '91', '98', '105'],
    answer: '91',
  },
  {
    id: 'tables-97',
    question: 'What is 14 x 6?',
    options: ['78', '82', '84', '88'],
    answer: '84',
  },
  {
    id: 'tables-98',
    question: 'What is 15 x 8?',
    options: ['105', '110', '120', '125'],
    answer: '120',
  },
  {
    id: 'tables-99',
    question: 'What is 16 x 7?',
    options: ['98', '104', '112', '120'],
    answer: '112',
  },
  {
    id: 'tables-100',
    question: 'What is 17 x 6?',
    options: ['96', '100', '102', '108'],
    answer: '102',
  },
];

const buildCalculatorOptions = (answer, seed = 0) => {
  const numericAnswer = Math.max(0, Math.floor(Number(answer) || 0));
  const options = new Set([numericAnswer]);
  const delta = Math.max(1, Math.round(Math.abs(numericAnswer) / 8));
  let cursor = 1;

  while (options.size < 4) {
    options.add(numericAnswer + delta * cursor);
    if (options.size < 4) {
      options.add(Math.max(0, numericAnswer - delta * cursor));
    }
    cursor += 1;
  }

  const ordered = [...options].slice(0, 4);
  const rotation = Math.max(0, seed % 4);
  return [...ordered.slice(rotation), ...ordered.slice(0, rotation)].map((value) => String(value));
};

const CALCULATOR_ADDITION_QUESTIONS = [
  ['What is 25 + 14?', 39],
  ['What is 88 + 12?', 100],
  ['What is 120 + 30?', 150],
  ['What is 47 + 26?', 73],
  ['What is 63 + 17?', 80],
  ['What is 95 + 5?', 100],
  ['What is 34 + 19?', 53],
  ['What is 76 + 24?', 100],
  ['What is 58 + 22?', 80],
  ['What is 109 + 11?', 120],
  ['What is 41 + 18?', 59],
  ['What is 67 + 33?', 100],
  ['What is 140 + 25?', 165],
  ['What is 29 + 16?', 45],
  ['What is 54 + 46?', 100],
  ['What is 32 + 28?', 60],
  ['What is 73 + 14?', 87],
  ['What is 81 + 19?', 100],
  ['What is 26 + 27?', 53],
  ['What is 115 + 35?', 150],
  ['What is 48 + 12?', 60],
  ['What is 99 + 1?', 100],
  ['What is 37 + 44?', 81],
  ['What is 62 + 18?', 80],
  ['What is 150 + 45?', 195],
];

const CALCULATOR_SUBTRACTION_QUESTIONS = [
  ['What is 50 - 15?', 35],
  ['What is 100 - 45?', 55],
  ['What is 250 - 50?', 200],
  ['What is 84 - 29?', 55],
  ['What is 120 - 35?', 85],
  ['What is 96 - 16?', 80],
  ['What is 75 - 28?', 47],
  ['What is 140 - 60?', 80],
  ['What is 91 - 41?', 50],
  ['What is 200 - 75?', 125],
  ['What is 63 - 17?', 46],
  ['What is 110 - 30?', 80],
  ['What is 88 - 19?', 69],
  ['What is 150 - 45?', 105],
  ['What is 72 - 22?', 50],
  ['What is 130 - 55?', 75],
  ['What is 99 - 44?', 55],
  ['What is 160 - 70?', 90],
  ['What is 57 - 18?', 39],
  ['What is 180 - 95?', 85],
  ['What is 104 - 24?', 80],
  ['What is 145 - 45?', 100],
  ['What is 70 - 26?', 44],
  ['What is 210 - 120?', 90],
  ['What is 135 - 35?', 100],
];

const CALCULATOR_MULTIPLICATION_QUESTIONS = [
  ['What is 7 x 8?', 56],
  ['What is 12 x 5?', 60],
  ['What is 15 x 3?', 45],
  ['What is 9 x 6?', 54],
  ['What is 11 x 4?', 44],
  ['What is 8 x 9?', 72],
  ['What is 13 x 2?', 26],
  ['What is 14 x 3?', 42],
  ['What is 16 x 5?', 80],
  ['What is 6 x 12?', 72],
  ['What is 10 x 10?', 100],
  ['What is 17 x 4?', 68],
  ['What is 18 x 3?', 54],
  ['What is 19 x 2?', 38],
  ['What is 20 x 5?', 100],
  ['What is 4 x 25?', 100],
  ['What is 5 x 14?', 70],
  ['What is 3 x 21?', 63],
  ['What is 12 x 8?', 96],
  ['What is 9 x 11?', 99],
  ['What is 7 x 12?', 84],
  ['What is 15 x 6?', 90],
  ['What is 8 x 13?', 104],
  ['What is 14 x 7?', 98],
  ['What is 16 x 6?', 96],
];

const CALCULATOR_DIVISION_QUESTIONS = [
  ['What is 40 / 5?', 8],
  ['What is 100 / 4?', 25],
  ['What is 81 / 9?', 9],
  ['What is 72 / 8?', 9],
  ['What is 60 / 3?', 20],
  ['What is 144 / 12?', 12],
  ['What is 96 / 6?', 16],
  ['What is 84 / 7?', 12],
  ['What is 56 / 8?', 7],
  ['What is 90 / 5?', 18],
  ['What is 120 / 10?', 12],
  ['What is 132 / 11?', 12],
  ['What is 63 / 3?', 21],
  ['What is 75 / 15?', 5],
  ['What is 108 / 9?', 12],
  ['What is 150 / 5?', 30],
  ['What is 64 / 4?', 16],
  ['What is 200 / 25?', 8],
  ['What is 98 / 7?', 14],
  ['What is 45 / 9?', 5],
  ['What is 160 / 8?', 20],
  ['What is 126 / 6?', 21],
  ['What is 180 / 12?', 15],
  ['What is 54 / 2?', 27],
  ['What is 210 / 7?', 30],
];

const CALCULATOR_PRACTICE_BLUEPRINT = [
  ...CALCULATOR_ADDITION_QUESTIONS,
  ...CALCULATOR_SUBTRACTION_QUESTIONS,
  ...CALCULATOR_MULTIPLICATION_QUESTIONS,
  ...CALCULATOR_DIVISION_QUESTIONS,
];

export const JUNIOR_CALCULATOR_QUIZ_QUESTIONS = CALCULATOR_PRACTICE_BLUEPRINT.map(
  ([question, answer], index) => ({
    id: `calculator-${index + 1}`,
    question,
    options: buildCalculatorOptions(answer, index + 1),
    answer: String(answer),
  })
);
