export const JUNIOR_QUIZ_REWARD_GEMS = 50;

export const JUNIOR_LAW_MILESTONE_SIZE = 10;
export const JUNIOR_LAW_MILESTONE_REWARD_GEMS = 15;

export const JUNIOR_SCIENCE_MILESTONE_SIZE = 10;
export const JUNIOR_SCIENCE_MILESTONE_REWARD_GEMS = 15;

export const JUNIOR_NUMBERS_MILESTONE_SIZE = 10;
export const JUNIOR_NUMBERS_MILESTONE_REWARD_GEMS = 15;

export const JUNIOR_TABLES_MILESTONE_SIZE = 10;
export const JUNIOR_TABLES_MILESTONE_REWARD_GEMS = 15;

// Keep this structure for easy edits:
// {
//   id: "law-1",
//   question: "Question text",
//   options: ["Option A", "Option B", "Option C", "Option D"],
//   answer: "Exact correct option text"
// }

export const JUNIOR_LAW_QUIZ_QUESTIONS = [
  {
    id: 'law-1',
    question: 'What does a Red Light mean at a traffic signal?',
    options: ['Stop', 'Drive faster', 'Keep honking', 'Turn right immediately'],
    answer: 'Stop',
  },
  {
    id: 'law-2',
    question: 'Do children have the Right to Education in school?',
    options: ['No', 'Only some children', 'Yes, all children', 'Only children in big cities'],
    answer: 'Yes, all children',
  },
  {
    id: 'law-3',
    question: 'When should you use a Zebra Crossing?',
    options: ['To race bicycles', 'To cross the road safely', 'To park your vehicle', 'To stop a bus'],
    answer: 'To cross the road safely',
  },
  {
    id: 'law-4',
    question: 'What should you do if a stranger offers you a chocolate?',
    options: ['Take it and keep it secret', 'Go with the stranger', 'Say No and tell your parents', 'Share it with friends'],
    answer: 'Say No and tell your parents',
  },
  {
    id: 'law-5',
    question: 'Where should you always throw garbage?',
    options: ['On the road', 'Out of the window', 'In the Dustbin', 'In the park'],
    answer: 'In the Dustbin',
  },
  {
    id: 'law-6',
    question: 'What is the emergency number for the Police?',
    options: ['101', '100 or 112', '108', '1098'],
    answer: '100 or 112',
  },
  {
    id: 'law-7',
    question: 'Is it legal for children to work in a factory?',
    options: ['Yes, if it is a holiday', 'Yes, if parents allow it', 'No, it is Child Labour and it is a crime', 'Yes, but only on weekends'],
    answer: 'No, it is Child Labour and it is a crime',
  },
  {
    id: 'law-8',
    question: 'How should we treat our National Flag (Tiranga)?',
    options: ['Ignore it', 'Use it carelessly', 'With great respect', 'Only click photos with it'],
    answer: 'With great respect',
  },
  {
    id: 'law-9',
    question: 'Is it okay to pluck flowers in a public park?',
    options: ['Yes, always', 'No, we must protect nature', 'Yes, only on Sundays', 'Yes, if friends say so'],
    answer: 'No, we must protect nature',
  },
  {
    id: 'law-10',
    question: 'Is bullying or teasing other children allowed?',
    options: ['Yes, for fun', 'No, we should be kind to everyone', 'Only after school', 'Only online'],
    answer: 'No, we should be kind to everyone',
  },
  {
    id: 'law-11',
    question: 'Why must we give way to an Ambulance?',
    options: ['To reduce noise', 'For fun', "To save someone's life", 'Because traffic police said so only'],
    answer: "To save someone's life",
  },
  {
    id: 'law-12',
    question: 'What should you do if the Fire Alarm rings at school?',
    options: ['Hide under your desk', 'Stay calm and exit immediately', 'Start recording a video', 'Try to switch off the alarm'],
    answer: 'Stay calm and exit immediately',
  },
  {
    id: 'law-13',
    question: 'Why is it important to wear a helmet while riding?',
    options: ['For style', 'For head safety', 'For school rules', 'Only for racing'],
    answer: 'For head safety',
  },
  {
    id: 'law-14',
    question: 'Why are there two types of dustbins (Green and Blue)?',
    options: ['For decoration', 'For school and home separately', 'To separate wet and dry waste', 'For big and small waste'],
    answer: 'To separate wet and dry waste',
  },
  {
    id: 'law-15',
    question: 'Which side of the road should we walk on in India?',
    options: ['Right side', 'Middle of the road', 'Left side', 'Any side'],
    answer: 'Left side',
  },
  {
    id: 'law-16',
    question: 'How should you stand during the National Anthem?',
    options: ['While talking', 'Still and in attention', 'Sitting down', 'While using your phone'],
    answer: 'Still and in attention',
  },
  {
    id: 'law-17',
    question: 'Do children have the Right to Expression (to speak their mind)?',
    options: ['No', 'Yes, their voice matters', 'Only during exams', 'Only at home'],
    answer: 'Yes, their voice matters',
  },
  {
    id: 'law-18',
    question: 'Is it safe to touch electric switches with wet hands?',
    options: ['Yes, it is safe', 'No, it is very dangerous', 'Only in winter', 'It does not matter'],
    answer: 'No, it is very dangerous',
  },
  {
    id: 'law-19',
    question: 'What kind of act is stealing?',
    options: ['A smart act', 'It is a bad act and a legal crime', 'Okay if the item is small', 'Only wrong in games'],
    answer: 'It is a bad act and a legal crime',
  },
  {
    id: 'law-20',
    question: 'What is the Constitution?',
    options: ['A school diary', 'The book of laws for the country', 'A map book', 'A story book'],
    answer: 'The book of laws for the country',
  },
  {
    id: 'law-21',
    question: 'What is the purpose of a CCTV camera?',
    options: ['To play music', 'To keep everyone safe', 'To switch lights on and off', 'To paint roads'],
    answer: 'To keep everyone safe',
  },
  {
    id: 'law-22',
    question: 'Whom should you talk to about Good Touch and Bad Touch?',
    options: ['No one', 'Only friends', 'Parents or Teachers', 'Online strangers'],
    answer: 'Parents or Teachers',
  },
  {
    id: 'law-23',
    question: 'What is the job of a Judge?',
    options: ['To umpire cricket matches', 'To decide what is right and wrong by law', 'To operate traffic lights', 'To drive school buses'],
    answer: 'To decide what is right and wrong by law',
  },
  {
    id: 'law-24',
    question: 'Is it legal to hurt animals?',
    options: ['Yes', 'No, they also have the right to live safely', 'Only in forests', 'Only small animals'],
    answer: 'No, they also have the right to live safely',
  },
  {
    id: 'law-25',
    question: 'Why is playing on the road forbidden?',
    options: ['Roads are dirty', 'Because of the risk of accidents', 'Because the ball can get lost', 'Because it is sunny'],
    answer: 'Because of the risk of accidents',
  },
  {
    id: 'law-26',
    question: 'Why must we stay quiet in a hospital?',
    options: ['Doctors may scold us', 'Patients need rest to recover', 'The gate will close', 'The TV will stop'],
    answer: 'Patients need rest to recover',
  },
  {
    id: 'law-27',
    question: 'What is Voting for adults?',
    options: ['A hobby', 'A legal right and responsibility', 'Time pass', 'A festival activity'],
    answer: 'A legal right and responsibility',
  },
  {
    id: 'law-28',
    question: 'What is the use of a Lost and Found desk?',
    options: ['To sell new items', 'To find missing items', 'To issue tickets', 'To host games'],
    answer: 'To find missing items',
  },
  {
    id: 'law-29',
    question: 'How should you behave in a public library?',
    options: ['Talk loudly', 'Read quietly and maintain silence', 'Run between shelves', 'Have a food party'],
    answer: 'Read quietly and maintain silence',
  },
  {
    id: 'law-30',
    question: 'Can children start a YouTube channel?',
    options: ['No', 'Only after age 18', 'Yes, with parental permission', 'Only if teachers allow'],
    answer: 'Yes, with parental permission',
  },
  {
    id: 'law-31',
    question: 'Who is known as the Father of the Indian Constitution?',
    options: ['Mahatma Gandhi', 'Dr. B.R. Ambedkar', 'Jawaharlal Nehru', 'Sardar Patel'],
    answer: 'Dr. B.R. Ambedkar',
  },
  {
    id: 'law-32',
    question: 'What is the minimum age to vote in India?',
    options: ['16 years', '17 years', '18 years', '21 years'],
    answer: '18 years',
  },
  {
    id: 'law-33',
    question: 'Is it allowed to write on the walls of historical monuments?',
    options: ['Yes, if using chalk', 'Yes, if no one is watching', 'No, it is a crime', 'Yes, with a marker only'],
    answer: 'No, it is a crime',
  },
  {
    id: 'law-34',
    question: "What is the head of a city's municipal corporation called?",
    options: ['Governor', 'Mayor', 'Collector', 'President'],
    answer: 'Mayor',
  },
  {
    id: 'law-35',
    question: 'What is the main job of the Supreme Court?',
    options: ['To collect taxes', 'To protect the law', 'To build roads', 'To run schools'],
    answer: 'To protect the law',
  },
  {
    id: 'law-36',
    question: 'Can children be forced to work in hazardous places?',
    options: ['Yes, if they are paid', 'Yes, if parents allow', 'No, it is strictly illegal', 'Yes, during vacations'],
    answer: 'No, it is strictly illegal',
  },
  {
    id: 'law-37',
    question: 'What does the blue wheel in the center of the Indian flag represent?',
    options: ['Victory', 'Peace', 'Dharma Chakra', 'Unity'],
    answer: 'Dharma Chakra',
  },
  {
    id: 'law-38',
    question: 'Is it legal to use a plastic bag if it is banned?',
    options: ['Yes, if reused', 'Yes, for shopping only', 'No, it is against the law', 'Yes, in small markets'],
    answer: 'No, it is against the law',
  },
  {
    id: 'law-39',
    question: 'What should you do if you find a lost wallet?',
    options: ['Keep it', 'Give it to a friend', 'Hand it over to the police', 'Throw it away'],
    answer: 'Hand it over to the police',
  },
  {
    id: 'law-40',
    question: "Do we have the 'Right to Equality'?",
    options: ['No', 'Only adults have it', 'Yes, everyone is equal before the law', 'Only rich people have it'],
    answer: 'Yes, everyone is equal before the law',
  },
  {
    id: 'law-41',
    question: 'What is the full form of FIR?',
    options: ['First Incident Record', 'Final Investigation Report', 'First Information Report', 'File Inspection Record'],
    answer: 'First Information Report',
  },
  {
    id: 'law-42',
    question: 'Who makes the laws for the whole country?',
    options: ['Municipal Corporation', 'Supreme Court', 'Parliament', 'Police Department'],
    answer: 'Parliament',
  },
  {
    id: 'law-43',
    question: 'Is it okay to use loud crackers late at night?',
    options: ['Yes, anytime', 'Yes, on weekends', 'No, it causes noise pollution', 'Yes, near highways'],
    answer: 'No, it causes noise pollution',
  },
  {
    id: 'law-44',
    question: "What is the 'Right to Information' (RTI)?",
    options: ['Right to own land', 'Right to ask for info from the government', 'Right to skip taxes', 'Right to vote at 16'],
    answer: 'Right to ask for info from the government',
  },
  {
    id: 'law-45',
    question: 'Can anyone be arrested without a reason?',
    options: ['Yes', 'No, there must be a legal reason', 'Yes, if police are busy', 'Only at night'],
    answer: 'No, there must be a legal reason',
  },
  {
    id: 'law-46',
    question: "What is a 'Cyber Crime'?",
    options: ['A crime in a market', 'A crime done using the internet or computers', 'A traffic violation', 'A school offense'],
    answer: 'A crime done using the internet or computers',
  },
  {
    id: 'law-47',
    question: 'Is it mandatory to wear a seatbelt in a car?',
    options: ['No', 'Yes, for safety and law', 'Only for drivers', 'Only on highways'],
    answer: 'Yes, for safety and law',
  },
  {
    id: 'law-48',
    question: "What is the 'Preamble' of the Constitution?",
    options: ['A punishment list', 'The introduction to the laws', 'A voting list', 'A police notice'],
    answer: 'The introduction to the laws',
  },
  {
    id: 'law-49',
    question: 'Can children under 14 work in tea stalls?',
    options: ['Yes', 'Only on holidays', 'No, it is child labour', 'Only with family permission'],
    answer: 'No, it is child labour',
  },
  {
    id: 'law-50',
    question: "What is the 'Right against Exploitation'?",
    options: ['Right to own property', 'Right to not be treated unfairly', 'Right to skip school', 'Right to free transport'],
    answer: 'Right to not be treated unfairly',
  },
  {
    id: 'law-51',
    question: 'Who is the head of a state government?',
    options: ['Prime Minister', 'Governor', 'Chief Minister', 'Mayor'],
    answer: 'Chief Minister',
  },
  {
    id: 'law-52',
    question: "What is the 'Rule of Law'?",
    options: ['Police can decide anything', 'Law is supreme for everyone', 'Only judges follow law', 'Only leaders follow law'],
    answer: 'Law is supreme for everyone',
  },
  {
    id: 'law-53',
    question: 'Is it legal to drive a vehicle without a license?',
    options: ['Yes, for short distance', 'No, it is a crime', 'Yes, if with parents', 'Only in villages'],
    answer: 'No, it is a crime',
  },
  {
    id: 'law-54',
    question: 'What do we call the person who fights a case in court?',
    options: ['Doctor', 'Lawyer/Advocate', 'Engineer', 'Teacher'],
    answer: 'Lawyer/Advocate',
    acceptedAnswers: ['Lawyer', 'Advocate'],
  },
  {
    id: 'law-55',
    question: 'Is education free for children in government schools?',
    options: ['No', 'Yes, up to age 14', 'Only till age 10', 'Only for boys'],
    answer: 'Yes, up to age 14',
  },
  {
    id: 'law-56',
    question: "What is 'Human Rights Day' celebrated for?",
    options: ['To celebrate sports', "To protect everyone's dignity", 'To celebrate elections', 'To celebrate money'],
    answer: "To protect everyone's dignity",
  },
  {
    id: 'law-57',
    question: 'Can you be punished twice for the same crime?',
    options: ['Yes', 'No, according to the law', 'Only in big crimes', 'Only by police'],
    answer: 'No, according to the law',
  },
  {
    id: 'law-58',
    question: "What is a 'Warrant'?",
    options: ['A school ID card', 'A legal paper to search or arrest', 'A tax form', 'A passport'],
    answer: 'A legal paper to search or arrest',
  },
  {
    id: 'law-59',
    question: 'Is it allowed to cut trees in a forest without permission?',
    options: ['Yes', 'Only in summer', 'No, it is illegal', 'Only if the tree is small'],
    answer: 'No, it is illegal',
  },
  {
    id: 'law-60',
    question: "What is the 'Right to Freedom of Religion'?",
    options: ['Right to avoid school', 'Right to follow any religion', 'Right to avoid taxes', 'Right to skip laws'],
    answer: 'Right to follow any religion',
  },
  {
    id: 'law-61',
    question: 'What is Lok Sabha?',
    options: ['Upper house of Parliament', 'Lower house of Parliament', 'State court', 'City council'],
    answer: 'Lower house of Parliament',
  },
  {
    id: 'law-62',
    question: 'What is Rajya Sabha?',
    options: ['Lower house of Parliament', 'Upper house of Parliament', 'High Court bench', 'Village council'],
    answer: 'Upper house of Parliament',
  },
  {
    id: 'law-63',
    question: 'Who is known as the first citizen of India?',
    options: ['Prime Minister', 'President of India', 'Chief Justice', 'Governor'],
    answer: 'President of India',
  },
  {
    id: 'law-64',
    question: 'What is PIL?',
    options: ['Public Identity License', 'Public Interest Litigation', 'Private Investigation Law', 'Police Information Letter'],
    answer: 'Public Interest Litigation',
  },
  {
    id: 'law-65',
    question: 'Is giving or taking a bribe legal?',
    options: ['Yes', 'No', 'Only in business', 'Only in emergencies'],
    answer: 'No',
  },
  {
    id: 'law-66',
    question: 'What should you do first if you see a road accident?',
    options: ['Record a video', 'Walk away', 'Call emergency services and help safely', 'Argue with drivers'],
    answer: 'Call emergency services and help safely',
  },
  {
    id: 'law-67',
    question: 'What is legal aid?',
    options: ['Paid legal advice only', 'Free legal help for those who cannot afford it', 'A police reward', 'A tax scheme'],
    answer: 'Free legal help for those who cannot afford it',
  },
  {
    id: 'law-68',
    question: 'Can a minor sign all legal contracts alone?',
    options: ['Yes', 'No, usually a guardian is needed', 'Only online', 'Only in school'],
    answer: 'No, usually a guardian is needed',
  },
  {
    id: 'law-69',
    question: 'What is public property?',
    options: ['Private home items', 'Property owned by government for everyone', 'Only school books', 'Personal vehicles'],
    answer: 'Property owned by government for everyone',
  },
  {
    id: 'law-70',
    question: 'Is damaging public property punishable?',
    options: ['No', 'Yes, it is an offense', 'Only in big cities', 'Only if reported by media'],
    answer: 'Yes, it is an offense',
  },
  {
    id: 'law-71',
    question: 'What is a traffic challan?',
    options: ['A driving badge', 'An official notice of fine for rule violation', 'A fuel bill', 'A parking permit'],
    answer: 'An official notice of fine for rule violation',
  },
  {
    id: 'law-72',
    question: 'What does a bailable offense mean?',
    options: ['No punishment', 'Can be released on bail', 'No court hearing', 'Only a warning'],
    answer: 'Can be released on bail',
  },
  {
    id: 'law-73',
    question: 'Can police search a home without legal authority in normal situations?',
    options: ['Yes, always', 'No, legal authority is required', 'Only in daytime', 'Only in villages'],
    answer: 'No, legal authority is required',
  },
  {
    id: 'law-74',
    question: 'What is consumer court used for?',
    options: ['Criminal trials only', 'Resolving consumer complaints', 'School disputes', 'Election disputes'],
    answer: 'Resolving consumer complaints',
  },
  {
    id: 'law-75',
    question: 'What is e-waste?',
    options: ['Food waste', 'Discarded electronic waste', 'Paper waste only', 'Plastic toys only'],
    answer: 'Discarded electronic waste',
  },
  {
    id: 'law-76',
    question: 'Can sharing someone personal data without consent be a legal issue?',
    options: ['No', 'Yes', 'Only for adults', 'Only on weekends'],
    answer: 'Yes',
  },
  {
    id: 'law-77',
    question: 'What does the juvenile justice system deal with?',
    options: ['Only property tax', 'Children in conflict with law', 'Road construction', 'Banking disputes'],
    answer: 'Children in conflict with law',
  },
  {
    id: 'law-78',
    question: 'What is a fundamental duty?',
    options: ['A hobby', 'A responsibility every citizen should follow', 'A private right', 'A school holiday'],
    answer: 'A responsibility every citizen should follow',
  },
  {
    id: 'law-79',
    question: 'Why should cyberbullying be reported?',
    options: ['To increase followers', 'To stop abuse and seek legal help', 'To make it viral', 'To ignore it'],
    answer: 'To stop abuse and seek legal help',
  },
  {
    id: 'law-80',
    question: 'What is the main aim of law in society?',
    options: ['To create fear', 'To maintain order and protect rights', 'To stop all fun', 'To reduce school time'],
    answer: 'To maintain order and protect rights',
  },
  {
    id: 'law-81',
    question: 'What is the official residence of the President of India called?',
    options: ['Rashtrapati Bhavan', 'Parliament House', 'Raj Bhavan', 'South Block'],
    answer: 'Rashtrapati Bhavan',
  },
  {
    id: 'law-82',
    question: 'Can a police officer arrest a woman after sunset without a special order?',
    options: ['Yes, always', 'No, it is protected by law', 'Yes, if there is traffic', 'Only on weekends'],
    answer: 'No, it is protected by law',
  },
  {
    id: 'law-83',
    question: "What is the 'Right to Privacy'?",
    options: ['Right to free transport', 'The right to keep your personal life private', 'Right to skip school', 'Right to own a vehicle'],
    answer: 'The right to keep your personal life private',
  },
  {
    id: 'law-84',
    question: 'Who is the supreme commander of the Indian Armed Forces?',
    options: ['The Prime Minister', 'The Home Minister', 'The President', 'The Chief of Army Staff'],
    answer: 'The President',
  },
  {
    id: 'law-85',
    question: "What is 'Child Helpline Number' in India?",
    options: ['100', '101', '1098', '112'],
    answer: '1098',
  },
  {
    id: 'law-86',
    question: 'Is it legal to buy or sell wild animals?',
    options: ['Yes, with friends', 'No, it is a crime against wildlife', 'Yes, in small markets', 'Only in villages'],
    answer: 'No, it is a crime against wildlife',
  },
  {
    id: 'law-87',
    question: "What is the 'Lokpal'?",
    options: ['A traffic police officer', 'An officer who investigates corruption', 'A school principal', 'A district judge'],
    answer: 'An officer who investigates corruption',
  },
  {
    id: 'law-88',
    question: 'Can you change your religion by your own choice?',
    options: ['No, never', 'Yes, it is a fundamental right', 'Only after 50 years', 'Only with police permission'],
    answer: 'Yes, it is a fundamental right',
  },
  {
    id: 'law-89',
    question: "What is a 'Public Interest Litigation' (PIL)?",
    options: ['A case filed for the benefit of the public', 'A private business contract', 'A school transfer letter', 'A tax payment notice'],
    answer: 'A case filed for the benefit of the public',
    acceptedAnswers: ['Public Interest Litigation', 'PIL'],
  },
  {
    id: 'law-90',
    question: "Is it mandatory to have an 'Aadhaar Card' for certain govt services?",
    options: ['No, never required', 'Yes, it is used for identification', 'Only for children', 'Only for tourists'],
    answer: 'Yes, it is used for identification',
  },
  {
    id: 'law-91',
    question: "What is the 'Juvenile Justice Act'?",
    options: ['Law for only adults', 'Special laws for children under 18', 'Rules for traffic police', 'Law for banks'],
    answer: 'Special laws for children under 18',
  },
  {
    id: 'law-92',
    question: 'Who appoints the Chief Justice of India?',
    options: ['The Parliament', 'The Prime Minister', 'The President', 'The Supreme Court Registry'],
    answer: 'The President',
  },
  {
    id: 'law-93',
    question: "What is the 'Right to Social Security'?",
    options: ['Support from the govt during old age or sickness', 'Right to own a school', 'Right to avoid taxes', 'Support only during festivals'],
    answer: 'Support from the govt during old age or sickness',
  },
  {
    id: 'law-94',
    question: 'Is child marriage legal in India?',
    options: ['Yes, with family permission', 'No, it is a punishable crime', 'Yes, in rural areas', 'Only in emergencies'],
    answer: 'No, it is a punishable crime',
  },
  {
    id: 'law-95',
    question: "What is the 'Blue Book' in Indian security?",
    options: ['A school attendance register', 'Rules for protecting VVIPs', 'A tax rule book', 'A law exam guide'],
    answer: 'Rules for protecting VVIPs',
  },
  {
    id: 'law-96',
    question: 'Can the Parliament change the Constitution?',
    options: ['No, never', 'Yes, but not its basic structure', 'Only during elections', 'Only state governments can do this'],
    answer: 'Yes, but not its basic structure',
  },
  {
    id: 'law-97',
    question: "What is 'Defamation'?",
    options: ['Damaging someone\'s reputation by lying', 'Helping people in court', 'A type of national holiday', 'A school punishment'],
    answer: "Damaging someone's reputation by lying",
  },
  {
    id: 'law-98',
    question: "Who is an 'NRI'?",
    options: ['National Road Inspector', 'Non-Resident Indian living abroad', 'New Resident of India', 'National Rights Investigator'],
    answer: 'Non-Resident Indian living abroad',
    acceptedAnswers: ['NRI', 'Non Resident Indian living abroad', 'Non Resident Indian'],
  },
  {
    id: 'law-99',
    question: "What is the 'National Green Tribunal' (NGT)?",
    options: ['A court for environmental cases', 'A sports committee', 'A school science club', 'A traffic control room'],
    answer: 'A court for environmental cases',
    acceptedAnswers: ['National Green Tribunal', 'NGT'],
  },
  {
    id: 'law-100',
    question: 'Is it legal to use a phone while driving?',
    options: ['Yes, if traffic is slow', 'No, it is a dangerous traffic violation', 'Only for short calls', 'Yes, with headphones'],
    answer: 'No, it is a dangerous traffic violation',
  },
];

export const JUNIOR_SCIENCE_QUIZ_QUESTIONS = [
  {
    id: 'science-1',
    question: 'Which planet is known as the Red Planet?',
    options: ['Mars', 'Venus', 'Jupiter', 'Mercury'],
    answer: 'Mars',
  },
  {
    id: 'science-2',
    question: 'What is the freezing point of water?',
    options: ['0C', '100C', '10C', '-10C'],
    answer: '0C',
    acceptedAnswers: ['0°C', '0 C', '0 degree celsius', '0 degrees celsius'],
  },
  {
    id: 'science-3',
    question: 'Which part of the plant is under the ground?',
    options: ['Leaves', 'Flowers', 'Roots', 'Stem'],
    answer: 'Roots',
  },
  {
    id: 'science-4',
    question: 'How many legs does a spider have?',
    options: ['6', '8', '10', '12'],
    answer: '8',
  },
  {
    id: 'science-5',
    question: 'What do we call a scientist who studies stars?',
    options: ['Biologist', 'Chemist', 'Astronomer', 'Geologist'],
    answer: 'Astronomer',
  },
  {
    id: 'science-6',
    question: 'Which force pulls everything toward the Earth?',
    options: ['Magnetism', 'Friction', 'Gravity', 'Electricity'],
    answer: 'Gravity',
  },
  {
    id: 'science-7',
    question: 'What is the largest land animal?',
    options: ['Blue Whale', 'Tiger', 'African Elephant', 'Giraffe'],
    answer: 'African Elephant',
  },
  {
    id: 'science-8',
    question: 'Which organ helps us breathe?',
    options: ['Heart', 'Lungs', 'Liver', 'Kidney'],
    answer: 'Lungs',
  },
  {
    id: 'science-9',
    question: 'Is the Sun a planet or a star?',
    options: ['A Planet', 'A Star', 'A Comet', 'A Satellite'],
    answer: 'A Star',
    acceptedAnswers: ['Star'],
  },
  {
    id: 'science-10',
    question: 'What is the hard outer layer of a tooth called?',
    options: ['Pulp', 'Dentin', 'Enamel', 'Gum'],
    answer: 'Enamel',
  },
  {
    id: 'science-11',
    question: 'Which gas do plants release during the day?',
    options: ['Carbon Dioxide', 'Nitrogen', 'Oxygen', 'Hydrogen'],
    answer: 'Oxygen',
  },
  {
    id: 'science-12',
    question: 'How many days does it take for Earth to orbit the Sun?',
    options: ['300 days', '365 days', '400 days', '730 days'],
    answer: '365 days',
  },
  {
    id: 'science-13',
    question: 'Which animal is the fastest on land?',
    options: ['Lion', 'Horse', 'Cheetah', 'Leopard'],
    answer: 'Cheetah',
  },
  {
    id: 'science-14',
    question: 'What is the boiling point of water?',
    options: ['80C', '90C', '100C', '120C'],
    answer: '100C',
    acceptedAnswers: ['100°C', '100 C', '100 degree celsius', '100 degrees celsius'],
  },
  {
    id: 'science-15',
    question: 'Which sense organ helps us taste food?',
    options: ['Nose', 'Tongue', 'Eyes', 'Ears'],
    answer: 'Tongue',
  },
  {
    id: 'science-16',
    question: 'What do we call the water that falls from clouds?',
    options: ['Snow', 'Mist', 'Rain', 'Steam'],
    answer: 'Rain',
  },
  {
    id: 'science-17',
    question: 'Which is the smallest bird in the world?',
    options: ['Sparrow', 'Parrot', 'Hummingbird', 'Crow'],
    answer: 'Hummingbird',
  },
  {
    id: 'science-18',
    question: 'What is the center of an atom called?',
    options: ['Electron', 'Nucleus', 'Proton', 'Orbit'],
    answer: 'Nucleus',
  },
  {
    id: 'science-19',
    question: 'How many kidneys does a human usually have?',
    options: ['1', '2', '3', '4'],
    answer: '2',
  },
  {
    id: 'science-20',
    question: 'Which metal is liquid at room temperature?',
    options: ['Iron', 'Copper', 'Mercury', 'Silver'],
    answer: 'Mercury',
  },
  {
    id: 'science-21',
    question: 'What is the process of plants making food called?',
    options: ['Respiration', 'Digestion', 'Photosynthesis', 'Evaporation'],
    answer: 'Photosynthesis',
  },
  {
    id: 'science-22',
    question: 'Which is the tallest animal on Earth?',
    options: ['Elephant', 'Horse', 'Giraffe', 'Camel'],
    answer: 'Giraffe',
  },
  {
    id: 'science-23',
    question: 'What protects the brain?',
    options: ['Skin', 'Rib Cage', 'Skull', 'Muscles'],
    answer: 'Skull',
  },
  {
    id: 'science-24',
    question: 'How many states of matter are there (Basic)?',
    options: ['2', '3: Solid, Liquid, Gas', '4', '5'],
    answer: '3: Solid, Liquid, Gas',
    acceptedAnswers: ['3', 'solid liquid gas'],
  },
  {
    id: 'science-25',
    question: 'What do you call a baby frog?',
    options: ['Cub', 'Pup', 'Tadpole', 'Larva'],
    answer: 'Tadpole',
  },
  {
    id: 'science-26',
    question: 'Which planet is famous for its rings?',
    options: ['Mars', 'Saturn', 'Earth', 'Venus'],
    answer: 'Saturn',
  },
  {
    id: 'science-27',
    question: 'What is the main source of energy for Earth?',
    options: ['Moon', 'The Sun', 'Wind', 'Coal'],
    answer: 'The Sun',
    acceptedAnswers: ['Sun'],
  },
  {
    id: 'science-28',
    question: 'Which instrument is used to see tiny germs?',
    options: ['Telescope', 'Microscope', 'Stethoscope', 'Periscope'],
    answer: 'Microscope',
  },
  {
    id: 'science-29',
    question: 'What is the white part of the eye called?',
    options: ['Iris', 'Pupil', 'Retina', 'Sclera'],
    answer: 'Sclera',
  },
  {
    id: 'science-30',
    question: "Which gas makes up most of the Earth's atmosphere?",
    options: ['Oxygen', 'Hydrogen', 'Nitrogen', 'Carbon Dioxide'],
    answer: 'Nitrogen',
  },
];

export const JUNIOR_NUMBERS_QUIZ_QUESTIONS = [
  {
    id: 'numbers-1',
    question: 'What number comes after 9?',
    options: ['8', '10', '11', '12'],
    answer: '10',
  },
  {
    id: 'numbers-2',
    question: 'What number comes before 50?',
    options: ['48', '49', '51', '52'],
    answer: '49',
  },
  {
    id: 'numbers-3',
    question: 'What is the smallest two-digit number?',
    options: ['1', '9', '10', '11'],
    answer: '10',
  },
  {
    id: 'numbers-4',
    question: 'What is the largest one-digit number?',
    options: ['8', '9', '10', '11'],
    answer: '9',
  },
  {
    id: 'numbers-5',
    question: 'Which of these is an even number?',
    options: ['23', '37', '48', '55'],
    answer: '48',
  },
  {
    id: 'numbers-6',
    question: 'Which of these is an odd number?',
    options: ['12', '24', '36', '45'],
    answer: '45',
  },
  {
    id: 'numbers-7',
    question: 'What is 7 + 5?',
    options: ['10', '11', '12', '13'],
    answer: '12',
  },
  {
    id: 'numbers-8',
    question: 'What is 15 - 6?',
    options: ['7', '8', '9', '10'],
    answer: '9',
  },
  {
    id: 'numbers-9',
    question: 'What is 9 x 2?',
    options: ['16', '18', '20', '22'],
    answer: '18',
  },
  {
    id: 'numbers-10',
    question: 'What is 20 / 4?',
    options: ['4', '5', '6', '8'],
    answer: '5',
  },
  {
    id: 'numbers-11',
    question: 'What is the place value of 5 in 58?',
    options: ['5', '50', '500', '8'],
    answer: '50',
  },
  {
    id: 'numbers-12',
    question: 'What number is made by 3 hundreds, 4 tens and 2 ones?',
    options: ['324', '342', '432', '243'],
    answer: '342',
  },
  {
    id: 'numbers-13',
    question: 'What is the Roman numeral for 10?',
    options: ['V', 'X', 'L', 'C'],
    answer: 'X',
  },
  {
    id: 'numbers-14',
    question: 'How many sides does a triangle have?',
    options: ['2', '3', '4', '5'],
    answer: '3',
  },
  {
    id: 'numbers-15',
    question: 'What is half of 100?',
    options: ['25', '40', '50', '60'],
    answer: '50',
  },
  {
    id: 'numbers-16',
    question: 'What is double of 14?',
    options: ['26', '27', '28', '29'],
    answer: '28',
  },
  {
    id: 'numbers-17',
    question: 'Which number is greater?',
    options: ['67', '76', '56', '66'],
    answer: '76',
  },
  {
    id: 'numbers-18',
    question: 'Which number is smaller?',
    options: ['91', '19', '29', '39'],
    answer: '19',
  },
  {
    id: 'numbers-19',
    question: 'Find the next number: 2, 4, 6, 8, ?',
    options: ['9', '10', '11', '12'],
    answer: '10',
  },
  {
    id: 'numbers-20',
    question: 'Find the next number: 5, 10, 15, 20, ?',
    options: ['22', '24', '25', '30'],
    answer: '25',
  },
  {
    id: 'numbers-21',
    question: 'What is 100 - 45?',
    options: ['45', '50', '55', '65'],
    answer: '55',
  },
  {
    id: 'numbers-22',
    question: 'What is 11 + 11?',
    options: ['20', '21', '22', '23'],
    answer: '22',
  },
  {
    id: 'numbers-23',
    question: 'What is one-quarter of 20?',
    options: ['4', '5', '6', '8'],
    answer: '5',
  },
  {
    id: 'numbers-24',
    question: 'How many months are there in one year?',
    options: ['10', '11', '12', '13'],
    answer: '12',
  },
  {
    id: 'numbers-25',
    question: 'How many minutes are there in one hour?',
    options: ['30', '45', '60', '90'],
    answer: '60',
  },
  {
    id: 'numbers-26',
    question: 'Which of these is a prime number?',
    options: ['9', '15', '21', '29'],
    answer: '29',
  },
  {
    id: 'numbers-27',
    question: 'What is 30 + 70?',
    options: ['90', '100', '110', '120'],
    answer: '100',
  },
  {
    id: 'numbers-28',
    question: 'What is 90 / 10?',
    options: ['7', '8', '9', '10'],
    answer: '9',
  },
  {
    id: 'numbers-29',
    question: 'If you have 3 tens and 6 ones, what is the number?',
    options: ['30', '33', '36', '63'],
    answer: '36',
  },
  {
    id: 'numbers-30',
    question: 'Which number is closest to 100?',
    options: ['89', '95', '99', '120'],
    answer: '99',
  },
];

export const JUNIOR_TABLES_QUIZ_QUESTIONS = [
  {
    id: 'tables-1',
    question: 'What is 2 x 3?',
    options: ['5', '6', '7', '8'],
    answer: '6',
  },
  {
    id: 'tables-2',
    question: 'What is 4 x 5?',
    options: ['18', '20', '22', '24'],
    answer: '20',
  },
  {
    id: 'tables-3',
    question: 'What is 6 x 7?',
    options: ['36', '40', '42', '48'],
    answer: '42',
  },
  {
    id: 'tables-4',
    question: 'What is 8 x 9?',
    options: ['64', '72', '81', '96'],
    answer: '72',
  },
  {
    id: 'tables-5',
    question: 'What is 9 x 9?',
    options: ['72', '81', '90', '99'],
    answer: '81',
  },
  {
    id: 'tables-6',
    question: 'What is 12 x 2?',
    options: ['22', '24', '26', '28'],
    answer: '24',
  },
  {
    id: 'tables-7',
    question: 'What is 11 x 3?',
    options: ['30', '33', '36', '39'],
    answer: '33',
  },
  {
    id: 'tables-8',
    question: 'What is 7 x 8?',
    options: ['49', '54', '56', '63'],
    answer: '56',
  },
  {
    id: 'tables-9',
    question: 'What is 5 x 6?',
    options: ['25', '30', '35', '40'],
    answer: '30',
  },
  {
    id: 'tables-10',
    question: 'What is 10 x 10?',
    options: ['90', '95', '100', '110'],
    answer: '100',
  },
  {
    id: 'tables-11',
    question: 'What is 3 x 12?',
    options: ['30', '33', '36', '39'],
    answer: '36',
  },
  {
    id: 'tables-12',
    question: 'What is 4 x 9?',
    options: ['28', '32', '36', '40'],
    answer: '36',
  },
  {
    id: 'tables-13',
    question: 'What is 6 x 6?',
    options: ['30', '32', '34', '36'],
    answer: '36',
  },
  {
    id: 'tables-14',
    question: 'What is 8 x 7?',
    options: ['48', '54', '56', '64'],
    answer: '56',
  },
  {
    id: 'tables-15',
    question: 'What is 12 x 12?',
    options: ['124', '132', '144', '156'],
    answer: '144',
  },
  {
    id: 'tables-16',
    question: 'What is 15 x 2?',
    options: ['28', '30', '32', '35'],
    answer: '30',
  },
  {
    id: 'tables-17',
    question: 'What is 14 x 3?',
    options: ['36', '40', '42', '44'],
    answer: '42',
  },
  {
    id: 'tables-18',
    question: 'What is 9 x 4?',
    options: ['27', '32', '36', '45'],
    answer: '36',
  },
  {
    id: 'tables-19',
    question: 'What is 13 x 5?',
    options: ['55', '60', '65', '70'],
    answer: '65',
  },
  {
    id: 'tables-20',
    question: 'What is 7 x 11?',
    options: ['70', '72', '77', '84'],
    answer: '77',
  },
  {
    id: 'tables-21',
    question: 'What is 16 x 2?',
    options: ['30', '32', '34', '36'],
    answer: '32',
  },
  {
    id: 'tables-22',
    question: 'What is 18 x 3?',
    options: ['48', '52', '54', '56'],
    answer: '54',
  },
  {
    id: 'tables-23',
    question: 'What is 25 x 4?',
    options: ['90', '95', '100', '105'],
    answer: '100',
  },
  {
    id: 'tables-24',
    question: 'What is 9 x 12?',
    options: ['96', '99', '108', '120'],
    answer: '108',
  },
  {
    id: 'tables-25',
    question: 'What is 6 x 11?',
    options: ['60', '64', '66', '72'],
    answer: '66',
  },
  {
    id: 'tables-26',
    question: 'What is 8 x 12?',
    options: ['88', '92', '96', '104'],
    answer: '96',
  },
  {
    id: 'tables-27',
    question: 'What is 17 x 5?',
    options: ['75', '80', '85', '90'],
    answer: '85',
  },
  {
    id: 'tables-28',
    question: 'What is 19 x 2?',
    options: ['36', '38', '40', '42'],
    answer: '38',
  },
  {
    id: 'tables-29',
    question: 'What is 20 x 7?',
    options: ['120', '130', '140', '150'],
    answer: '140',
  },
  {
    id: 'tables-30',
    question: 'What is 15 x 6?',
    options: ['75', '80', '85', '90'],
    answer: '90',
  },
];
