-- Character gem balance columns
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS aiko_gems INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS niko_gems INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS kinu_gems INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS mimi_gems INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS miko_gems INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS chiko_gems INTEGER DEFAULT 0;

-- Card unlock tracking
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS unlocked_cards TEXT[] DEFAULT '{}';
